# Comparing the Old and the New.

In [1]:
# Import Library 

import re
import requests
import unicodedata
from bs4 import BeautifulSoup
from pprint import pprint
import numpy as np
from numpy import array
import pandas as pd 
import csv
import pickle
from IPython.display import display
import pickle
from collections import Counter
pd.set_option('display.max_columns', 100)
pd.set_option('display.precision',20)

### Older Filing

In [2]:
# Sample: Older filing style. 
import pickle
pd.set_option('display.max_columns', 100)
with open("0001564590-16-013195-10-K.csv", "rb") as fp:
    file = pickle.load(fp)
df01 = file[0]

print(df01.shape)

(1, 40)

### Newer Filing

In [3]:
# Sample: Newer filing style. 
import pickle 
pd.set_option('display.max_columns', 100)
with open("0001564590-20-019931-10-Q.csv", "rb") as fp:
    file = pickle.load(fp)
df02 = file[0]

print(df02.shape)

(1, 42)

# Loading

In [4]:
QorK = {
    '10-Q': ['0001564590-20-019931', '0001564590-19-038256', '0001564590-19-026445', '0001564590-19-013462', '0001564590-18-026353', '0001564590-18-019254', '0001564590-18-011086', '0001564590-17-021343', '0001564590-17-015705', '0001564590-17-009968', '0001564590-16-026820', '0001564590-16-023024', '0001564590-16-018886', '0001564590-15-009741', '0001564590-15-006666', '0001564590-15-003789'],
    '10-K': ['0001564590-20-004475', '0001564590-19-003165', '0001564590-18-002956', '0001564590-17-003118', '0001564590-16-013195', '0001564590-15-001031']}

In [5]:
def duplicate_columns( DataF ):
    
    duplicates = [k for (k,v) in Counter(DataF.columns).items() if v > 1] 

    for dupli in duplicates: 
        res = DataF[dupli].values.sum()
        DataF['Total {}'.format(dupli)] = res
        DataF.drop(dupli, axis=1, inplace=True)

    return DataF

In [6]:
df_list =[]
for k, v in QorK.items():
            
    for i, vv in enumerate(v):

        #with open("{}-{}.csv".format(v[i], k), "rb") as fp:
            #file = pickle.load(fp)
            #df = file[0]
        df = pd.read_pickle( "{}-{}.csv".format(v[i], k)  )
        df[0]['Filing/Acc.No.'] = '{}, {}'.format(k, vv)
        df_list.append( duplicate_columns(df[0]) )
        
        abt = pd.concat(df_list, sort=False)

In [7]:
abt.reset_index(drop=True, inplace=True)

abt[ 'Convertible Senior Notes'].fillna(0, inplace=True)
abt[ 'Total Convertible Senior Notes'].fillna(0, inplace=True)
CSN_sum = abt['Total Convertible Senior Notes'] + abt['Convertible Senior Notes']
abt['New_CSN'] = CSN_sum
abt.drop(['Convertible Senior Notes', 'Total Convertible Senior Notes'], axis=1, inplace=True)

In [8]:
def del_empty_col( df ):
    
    for columns in df:
        
        df.replace(0, np.nan, inplace=True)
        
        if df[columns].isna().astype(int).mean() > 0.1:
            df.drop([columns], inplace=True, axis=1)
            
    df.fillna(0)
        
    return df

In [9]:
del_empty_col(abt).fillna(0)

,Quarter,Year,Cash and cash equivalents,Accounts receivable,Inventory,Prepaid expenses and other current assets,Total current assets,"Operating lease vehicles, net","Property, plant and equipment, net",Total assets,Accounts payable,Accrued Liabilities,Customer deposits,Total current liabilities,Other long-term liabilities,Total liabilities,Additional paid-in capital,Accumulated deficit,Total stockholders' equity,Total liabilities and equity,Filing/Acc.No.,Total Deferred Revenue,Restricted cash,Other assets
0,Q1,2020,8080000000,1274000000,4494000000,1045000000,14893000000,2527000000,10638000000,37250000000,3970000000,2825000000,788000000,11986000000,2667000000,26518000000,15390000000,6104000000,9173000000,37250000000,"10-Q, 0001564590-20-019931",2385000000,0.0,0.0
1,Q3,2019,5338000000,1128000000,3581000000,660000000,10940000000,2253000000,10190000000,32795000000,3468000000,2497000000,665000000,10146000000,2676000000,25313000000,12348000000,6188000000,6040000000,32795000000,"10-Q, 0001564590-19-038256",2185000000,233000000.0,820000000.0
2,Q2,2019,4954740000,1147100000,3382358000,569748000,10181952000,2069540000,10082458000,31872597000,3133587000,2622943000,631107000,9588773000,2655720000,24722136000,12052458000,6331639000,5715393000,31872597000,"10-Q, 0001564590-19-026445",2065335000,128006000.0,842978000.0
3,Q1,2019,2198169000,1046945000,3836850000,464908000,7677822000,1972502000,9850929000,28912524000,3248827000,2276951000,768276000,9242800000,2475135000,22874618000,10563746000,5923305000,4605596000,28912524000,"10-Q, 0001564590-19-013462",1920153000,130950000.0,801867000.0
4,Q3,2018,2967504000,1155001000,3314127000,325232000,7920491000,2186137000,11246295000,29262713000,3596984000,1990095000,905838000,9775324000,2555319000,23409144000,9957711000,5457315000,4508838000,29262713000,"10-Q, 0001564590-18-026353",1521046000,158627000.0,431819000.0
5,Q2,2018,2236424000,569874000,3324643000,422034000,6699797000,2282047000,10969348000,27910000000,3030493000,1814979000,942129000,9141362000,2607458000,22642887000,9656537000,5768831000,3906421000,27910000000,"10-Q, 0001564590-18-019254",1372141000,146822000.0,419254000.0
6,Q1,2018,2665673000,652848000,2565826000,379379000,6383920000,2315124000,10519226000,27271429000,2603498000,1898431000,984823000,8650359000,2561886000,21551021000,9418896000,5051292000,4450695000,27271429000,"10-Q, 0001564590-18-011086",1354715000,120194000.0,415478000.0
7,Q3,2017,3530030000,607734000,2471382000,321406000,7068733000,3834234000,9394397000,28107074000,2385778000,1477784000,686084000,6468940000,2382830000,21929057000,8989022000,4298960000,4711480000,28107074000,"10-Q, 0001564590-17-021343",2034604000,138181000.0,231849000.0
8,Q2,2017,3035924000,453539000,2438111000,313501000,6359444000,3600821000,8399229000,26043705000,2359316000,1510744000,603540000,6546355000,2259538000,19459902000,8774212000,3679584000,5105752000,26043705000,"10-Q, 0001564590-17-015705",1948977000,118369000.0,209986000.0
9,Q1,2017,4006593000,440349000,2220336000,271665000,7027889000,3452595000,7016551000,25053726000,2075333000,1460367000,616398000,6245439000,2081822000,18885353000,8351514000,3343187000,4987719000,25053726000,"10-Q, 0001564590-17-009968",1796572000,88946000.0,224536000.0
10,Q3,2016,3084257000,326895000,1604571000,132978000,5172412000,2949297000,4309048000,12592397000,1606284000,695018000,690364000,4082390000,737559000,9900639000,5530928000,2875900000,2680488000,12592397000,"10-Q, 0001564590-16-026820",1207101000,90994000.0,70646000.0
11,Q2,2016,3246301000,178594000,1609607000,144678000,5203705000,2533726000,3993250000,11868952000,1114878000,558212000,679834000,3766404000,612344000,9311512000,5383731000,2897778000,2520294000,11868952000,"10-Q, 0001564590-16-023024",1092069000,71621000.0,66650000.0
12,Q1,2016,1441789000,318056000,1301961000,153757000,3239543000,2244210000,3593014000,9191702000,1013486000,438522000,391363000,3187699000,426611000,8178711000,3561256000,2604590000,970365000,9191702000,"10-Q, 0001564590-16-018886",1013617000,47783000.0,67152000.0
13,Q3,2015,1426036000,119964000,1293717000,133855000,2998795000,1360725000,3103811000,7547497000,824861000,373859000,269545000,2553771000,336505000,6186660000,3340436000,2001926000,1314656000,7547497000,"10-Q, 0001564590-15-009741",710378000,26355000.0,57811000.0
14,Q2,2015,1150673000,138648000,1212279000,106430000,2628621000,1120246000,2646017000,6468185000,771637000,345401000,272848000,2384388000,258142000,5701978000,2502679000,1772068000,715934000,6468185000,"10-Q, 0001564590-15-006666",623155000,19774000.0,53527000.0
15,Q1,2015,1510076000,200052000,1054840000,135756000,2921417000,912061000,2224191000,6120030000,732331000,353768000,249476000,2192381000,228367000,5239756000,2429677000,1587841000,825997000,6120030000,"10-Q, 0001564590-15-003789",539324000,13846000.0,48515000.0
16,Q4,2019,6268000000,1324000000,3552000000,713000000,12103000000,2447000000,10396000000,34309000000,3771000000,2905000000,726000000,10667000000,2655000000,26199000000,12737000000,6083000000,6618000000,34309000000,"10-K, 0001564590-20-004475",2370000000,246000000.0,808000000.0
17,Q4,2018,3685618000,949022000,3113446000,365671000,8306308000,2089758000,11330077000,29739614000,3404451000,2094253000,792601000,9992136000,2710403000,23426010000,10249120000,5317832000,4923243000,29739614000,"10-K, 0001564590-19-003165",1621165000,192551000.0,571657000.0
18,Q4,2017,3367914000,515381000,2263537000,268365000,6570520000,4116604000,10027522000,28655372000,2390250000,1731366000,853919000,7674670000,2442970000,23022980000,9178024000,4974299000,4237242000,28655372000,"10-K, 0001564590-18-002956",2193052000,155323000.0,273123000.0
19,Q4,2016,3393216000,499142000,2067454000,194465000,6259796000,3134080000,5982957000,22664076000,1860341000,1210028000,663859000,5827005000,1891449000,16750167000,7773727000,2997237000,4752911000,22664076000,"10-K, 0001564590-17-003118",1614916000,105519000.0,216751000.0
20,Q4,2015,1196908000,168965000,1277838000,125229000,2791568000,1791403000,3403334000,8092460000,916148000,422798000,283370000,2816274000,364976000,6961471000,3414692000,2322323000,1088944000,8092460000,"10-K, 0001564590-16-013195",870066000,31522000.0,74633000.0
21,Q4,2014,1905713000,226604000,953675000,94718000,3198657000,766744000,1829267000,5849251000,777946000,268884000,257587000,2107166000,173244000,4879345000,2345266000,1433682000,911710000,5849251000,"10-K, 0001564590-15-001031",483922000,11374000.0,43209000.0

In [10]:
# Just for checking.
def checking_duplicate_columns( DataF ):
    
    duplicates = [k for (k,v) in Counter(DataF.columns).items() if v > 1] 

    
    print('Shape of df: ', DataF.shape )
    return duplicates

In [11]:
checking_duplicate_columns(abt)

Shape of df:  (22, 24)

[]

https://stackoverflow.com/questions/50950614/converting-column-into-multi-index-column