# Comparing the Old and the New.

In [1]:
# Import Library 

import re
import requests
import unicodedata
from bs4 import BeautifulSoup
from pprint import pprint
import numpy as np
from numpy import array
import pandas as pd 
import csv
import pickle
from IPython.display import display
import pickle
from collections import Counter
pd.set_option('display.max_columns', 200)
pd.set_option('display.precision',20)
from IPython.core import display as ICD

# Loading

In [2]:
QorK = {'10-Q': ['0001018724-20-000010',
  '0001018724-19-000089',
  '0001018724-19-000071',
  '0001018724-19-000043',
  '0001018724-18-000159',
  '0001018724-18-000108',
  '0001018724-18-000072',
  '0001018724-17-000135',
  '0001018724-17-000100',
  '0001018724-17-000051',
  '0001018724-16-000324',
  '0001018724-16-000286',
  '0001018724-16-000227',
  '0001018724-15-000126',
  '0001018724-15-000087',
  '0001018724-15-000038',
  '0001018724-14-000055',
  '0001018724-14-000025',
  '0001018724-14-000014',
  '0001445305-13-002495',
  '0001193125-13-303204',
  '0001193125-13-174667',
  '0001193125-12-436012',
  '0001193125-12-317409',
  '0001193125-12-187203',
  '0001193125-11-280739',
  '0001193125-11-197823',
  '0001193125-11-110197',
  '0001193125-10-233883',
  '0001193125-10-164083',
  '0001193125-10-090367',
  '0001193125-09-212134',
  '0001193125-09-154174',
  '0001193125-09-085983',
  '0001193125-08-214483',
  '0001193125-08-157451',
  '0001193125-08-089548'],
 '10-K': ['0001018724-20-000004',
  '0001018724-19-000004',
  '0001018724-18-000005',
  '0001018724-17-000011',
  '0001018724-16-000172',
  '0001018724-15-000006',
  '0001018724-14-000006',
  '0001193125-13-028520',
  '0001193125-12-032846',
  '0001193125-11-016253',
  '0001193125-10-016098',
  '0001193125-09-014406',
  '0001193125-08-024707']}

In [3]:
def duplicate_columns( DataF ):
    
    try: 
        DataF.drop(DataF[None], axis =1, inplace=True)
        
    except:
        pass 
    
    new_col = list(DataF.columns)

    clean_col = [column.strip() for column in new_col]

    DataF.set_axis(clean_col, axis=1, inplace=True)
    
    duplicates = [col_name for (col_name,freq) in Counter(DataF.columns).items() if freq > 1] 
    print('{} duplicates '.format(len(duplicates)), duplicates, '\n')
    
    for dupli in duplicates: 
#         print(type(DataF[dupli].values))            
        
        try:
            res = DataF[dupli].fillna(0).values.sum()
            DataF['Total {}'.format(dupli)] = res
            DataF.drop(columns =dupli, axis=1, inplace=True)

        except: 
            DataF.drop(columns =dupli, axis=1, inplace=True)

        #DataF.drop(dupli, axis=1, inplace=True)
        
    return DataF

In [4]:
df_list =[]
for k, v in QorK.items():
            
    for i, vv in enumerate(v):
        print(vv, k)
        
        if k == '10-Q':
            
            df = pd.read_pickle( "{}-{}.csv".format(v[i], k))

            
        elif k == '10-K':
            dfs = pd.read_pickle( "{}-{}.csv".format(v[i], k))
            dft = dfs[0]
            df = dft.drop(dft.index[0]).reset_index(drop=True)
            
        df = duplicate_columns(df)  
        
        # Add unique identity to row 
        df['Filing/Acc.No.'] = '{}, {}'.format(k, vv)
        # handle duplicate column name
        df_list.append( df)

        ICD.display(df)

0001018724-20-000010 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Operating leases,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term lease liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 521 and 522,Outstanding shares 498 and 499,Treasury stock,Additional paid in capital,Accumulated other comprehensive income,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2020,None,None,27201000000,22091000000,18857000000,17836000000,85985000000,77779000000,26279000000,14739000000,16456000000,221238000000,None,40056000000,30791000000,8864000000,79711000000,40300000000,23437000000,12518000000,None,None,None,None,None,None,None,5000000,1837000000,35412000000,2063000000,33755000000,221238000000,65272000000,"10-Q, 0001018724-20-000010"

0001018724-19-000089 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Operating leases,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term lease liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 514 and 519,Outstanding shares 491 and 495,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q3,2019,None,None,23255000000,20146000000,18766000000,16887000000,79054000000,67662000000,None,14734000000,14535000000,199099000000,None,35794000000,28961000000,7381000000,72136000000,37058000000,22472000000,10925000000,None,None,None,None,None,None,None,5000000,1837000000,31817000000,1429000000,27952000000,199099000000,56508000000,"10-Q, 0001018724-19-000089"

0001018724-19-000071 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Operating leases,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term lease liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 514 and 518,Outstanding shares 491 and 494,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q2,2019,None,None,22616000000,18847000000,18580000000,16747000000,76790000000,64723000000,None,14727000000,13462000000,191351000000,None,36063000000,26140000000,7475000000,69678000000,35134000000,23329000000,10149000000,None,None,None,None,None,None,None,5000000,1837000000,30035000000,960000000,25818000000,191351000000,53061000000,"10-Q, 0001018724-19-000071"

0001018724-19-000043 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Operating leases,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term lease liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 514 and 516,Outstanding shares 491 and 492,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2019,None,None,23115000000,13905000000,16432000000,15979000000,69431000000,61048000000,None,14708000000,12783000000,178102000000,None,31809000000,24588000000,7298000000,63695000000,33275000000,23322000000,9400000000,None,None,None,None,None,None,None,5000000,1837000000,28059000000,1010000000,23193000000,178102000000,48410000000,"10-Q, 0001018724-19-000043"

0001018724-18-000159 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 507 and 512,Outstanding shares 484 and 489,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q3,2018,None,None,20425000000,9340000000,15862000000,14258000000,59885000000,58019000000,14553000000,11238000000,143695000000,None,30904000000,18420000000,6000000000,55324000000,24684000000,24562000000,None,None,None,None,None,None,None,5000000,1837000000,25375000000,1034000000,16616000000,143695000000,39125000000,"10-Q, 0001018724-18-000159"

0001018724-18-000108 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 507 and 511,Outstanding shares 484 and 487,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q2,2018,None,None,19823000000,7227000000,14824000000,12607000000,54481000000,54768000000,13944000000,10907000000,134100000000,None,27657000000,17140000000,6004000000,50801000000,24638000000,23666000000,None,None,None,None,None,None,None,5000000,1837000000,24028000000,934000000,13733000000,134100000000,34995000000,"10-Q, 0001018724-18-000108"

0001018724-18-000072 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 507 and 508,Outstanding shares 484 and 485,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2018,None,None,16676000000,8287000000,13840000000,12026000000,50829000000,52331000000,13388000000,9814000000,126362000000,None,25172000000,16691000000,6182000000,48045000000,24640000000,22214000000,None,None,None,None,None,None,None,5000000,1837000000,22563000000,467000000,11199000000,126362000000,31463000000,"10-Q, 0001018724-18-000072"

0001018724-17-000135 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 500 and 505,Outstanding shares 477 and 482,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q3,2017,None,None,12767000000,11543000000,13711000000,10557000000,48578000000,45335000000,13271000000,8083000000,115267000000,None,26075000000,15844000000,5153000000,47072000000,24710000000,18827000000,None,None,None,None,None,None,None,5000000,1837000000,20212000000,501000000,6779000000,115267000000,24658000000,"10-Q, 0001018724-17-000135"

0001018724-17-000100 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 500 and 504,Outstanding shares 477 and 480,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q2,2017,None,None,13203000000,8248000000,11510000000,8046000000,41007000000,37083000000,4254000000,5437000000,87781000000,None,21439000000,14016000000,5065000000,40520000000,7683000000,16364000000,None,None,None,None,None,None,None,5000000,1837000000,19129000000,607000000,6524000000,87781000000,23214000000,"10-Q, 0001018724-17-000100"

0001018724-17-000051 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 500 and 501,Outstanding shares 477 and 478,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2017,None,None,15440000000,6091000000,10600000000,7329000000,39460000000,32632000000,3823000000,5054000000,80969000000,None,18891000000,13054000000,5454000000,37399000000,7691000000,14205000000,None,None,None,None,None,None,None,5000000,1837000000,17976000000,797000000,6327000000,80969000000,21674000000,"10-Q, 0001018724-17-000051"

0001018724-16-000324 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 498 and 494,Outstanding shares 475 and 471,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q3,2016,None,None,13656000000,4691000000,10696000000,6566000000,35609000000,27177000000,3815000000,4296000000,70897000000,None,18801000000,10497000000,4200000000,33498000000,8205000000,11412000000,None,None,None,None,None,None,None,5000000,1837000000,15968000000,521000000,4167000000,70897000000,17782000000,"10-Q, 0001018724-16-000324"

0001018724-16-000286 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 497 and 494,Outstanding shares 474 and 471,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q2,2016,None,None,12521000000,4019000000,9588000000,6092000000,32220000000,25190000000,3774000000,3892000000,65076000000,None,16123000000,9613000000,3851000000,29587000000,8212000000,10739000000,None,None,None,None,None,None,None,5000000,1837000000,15026000000,571000000,3915000000,65076000000,16538000000,"10-Q, 0001018724-16-000286"

0001018724-16-000227 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 495 and 494,Outstanding shares 472 and 471,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2016,None,None,12470000000,3389000000,9582000000,5072000000,30513000000,23308000000,3785000000,3522000000,61128000000,None,14990000000,9431000000,3766000000,28187000000,8219000000,9966000000,None,None,None,None,None,None,None,5000000,1837000000,14144000000,614000000,3058000000,61128000000,14756000000,"10-Q, 0001018724-16-000227"

0001018724-15-000126 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 492 and 488,Outstanding shares 469 and 465,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q3,2015,None,None,10709000000,3719000000,8981000000,5440000000,28849000000,20636000000,3529000000,3216000000,56230000000,None,14437000000,9157000000,3063000000,26657000000,8243000000,8900000000,None,None,None,None,None,None,None,5000000,1837000000,12874000000,675000000,2063000000,56230000000,12430000000,"10-Q, 0001018724-15-000126"

0001018724-15-000087 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 491 and 488,Outstanding shares 468 and 465,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q2,2015,None,None,10269000000,3732000000,7470000000,4920000000,26391000000,19479000000,3523000000,3047000000,52440000000,None,12391000000,8959000000,2562000000,23912000000,8250000000,8510000000,None,None,None,None,None,None,None,5000000,1837000000,12233000000,617000000,1984000000,52440000000,11768000000,"10-Q, 0001018724-15-000087"

0001018724-15-000038 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 489 and 488,Outstanding shares 466 and 465,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2015,None,None,10237000000,3544000000,7369000000,4772000000,25922000000,17736000000,3491000000,2926000000,50075000000,None,11917000000,8840000000,2420000000,23177000000,8257000000,7768000000,None,None,None,None,None,None,None,5000000,1837000000,11565000000,752000000,1892000000,50075000000,10873000000,"10-Q, 0001018724-15-000038"

0001018724-14-000055 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 487 and 483,Outstanding shares 463 and 459,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q3,2014,None,None,5258000000,1625000000,7316000000,4373000000,18572000000,15702000000,3332000000,2813000000,40419000000,None,11811000000,7217000000,1814000000,20842000000,3099000000,6142000000,None,None,None,None,None,None,None,5000000,1837000000,10827000000,394000000,1735000000,40419000000,10336000000,"10-Q, 0001018724-14-000055"

0001018724-14-000025 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 486 and 483,Outstanding shares 462 and 459,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q2,2014,None,None,5057000000,2929000000,6644000000,4125000000,18755000000,14089000000,2677000000,2377000000,37898000000,None,10457000000,6688000000,1606000000,18751000000,3119000000,5426000000,None,None,None,None,None,None,None,5000000,1837000000,10405000000,143000000,2172000000,37898000000,10602000000,"10-Q, 0001018724-14-000025"

0001018724-14-000014 10-Q
1 duplicates  ['Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 484 and 483,Outstanding shares 460 and 459,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2014,None,None,5074000000,3592000000,6716000000,3945000000,19327000000,12267000000,2653000000,2117000000,36364000000,None,10590000000,6251000000,1516000000,18357000000,3147000000,4532000000,None,None,None,None,None,None,None,5000000,1837000000,10019000000,157000000,2298000000,36364000000,10328000000,"10-Q, 0001018724-14-000014"

0001445305-13-002495 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 481 and 478,Outstanding shares 458 and 454,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q3,2013,None,None,3872000000,3817000000,6068000000,3057000000,17334000000,9991000000,2635000000,1773000000,31861000000,None,10037000000,6098000000,16135000000,3043000000,3596000000,None,None,None,None,None,None,None,5000000,1837000000,9175000000,206000000,1950000000,31861000000,648000000,9087000000,"10-Q, 0001445305-13-002495"

0001193125-13-303204 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 480 and 478,Outstanding shares 457 and 454,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q2,2013,None,None,3704000000,3759000000,5420000000,2861000000,16285000000,8789000000,2614000000,1807000000,29623000000,None,8990000000,5745000000,14735000000,3042000000,3113000000,None,None,None,None,None,None,None,5000000,1837000000,8893000000,319000000,1991000000,29623000000,669000000,8733000000,"10-Q, 0001193125-13-303204"

0001193125-13-174667 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 479 and 478,Outstanding shares 455 and 454,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2013,None,None,4481000000,3414000000,5395000000,2516000000,16313000000,7674000000,2535000000,1732000000,28377000000,None,8916000000,5416000000,14332000000,3040000000,2573000000,None,None,None,None,None,None,None,5000000,1837000000,8585000000,319000000,1998000000,28377000000,630000000,8432000000,"10-Q, 0001193125-13-174667"

0001193125-12-436012 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 476 and 473,Outstanding shares 453 and 455,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q3,2012,None,None,2980000000,2268000000,5065000000,2392000000,13118000000,5662000000,2540000000,1476000000,22834000000,None,8369000000,4236000000,12605000000,2676000000,None,None,None,None,None,None,None,5000000,1837000000,7863000000,296000000,1818000000,22834000000,451000000,7553000000,"10-Q, 0001193125-12-436012"

0001193125-12-317409 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 476 and 473,Outstanding shares 452 and 455,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q2,2012,None,None,2335000000,2635000000,4380000000,2035000000,11793000000,5097000000,2521000000,1585000000,21022000000,None,7072000000,3892000000,10964000000,2553000000,None,None,None,None,None,None,None,5000000,1837000000,7573000000,328000000,2092000000,21022000000,434000000,7505000000,"10-Q, 0001193125-12-317409"

0001193125-12-187203 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 474 and 473,Outstanding shares 450 and 455,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2012,None,None,2288000000,3427000000,4255000000,1813000000,12154000000,4653000000,1970000000,1535000000,20339000000,None,6886000000,3602000000,10488000000,2580000000,None,None,None,None,None,None,None,5000000,1837000000,7192000000,174000000,2085000000,20339000000,398000000,7271000000,"10-Q, 0001193125-12-187203"

0001193125-11-280739 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 471 and 468,Outstanding shares 455 and 451,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q3,2011,None,None,2823000000,3503000000,3770000000,1496000000,11904000000,3999000000,1934000000,1190000000,19054000000,None,6552000000,2426000000,8978000000,2310000000,None,None,None,0,None,None,None,5000000,600000000,6824000000,241000000,1778000000,19054000000,339000000,7766000000,"10-Q, 0001193125-11-280739"

0001193125-11-197823 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 471 and 468,Outstanding shares 454 and 451,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q2,2011,None,None,2047000000,4308000000,3229000000,1438000000,11279000000,3470000000,1909000000,1253000000,17941000000,None,5721000000,2324000000,8045000000,2131000000,None,None,None,None,None,None,None,5000000,600000000,6675000000,30000000,1715000000,17941000000,287000000,7765000000,"10-Q, 0001193125-11-197823"

0001193125-11-110197 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 469 and 468,Outstanding shares 452 and 451,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2011,None,None,2641000000,4240000000,2888000000,1304000000,11288000000,2902000000,1513000000,1151000000,16882000000,None,5540000000,2190000000,7730000000,1805000000,None,None,None,None,None,None,None,5000000,600000000,6483000000,66000000,1525000000,16882000000,243000000,7347000000,"10-Q, 0001193125-11-110197"

0001193125-10-233883 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 466 and 461,Outstanding shares 449 and 444,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q3,2010,None,None,1539000000,4346000000,2515000000,959000000,9559000000,2099000000,1277000000,1184000000,14162000000,None,4614000000,1761000000,6375000000,164000000,1226000000,None,None,None,None,None,None,None,5000000,600000000,6215000000,131000000,908000000,14162000000,243000000,6397000000,"10-Q, 0001193125-10-233883"

0001193125-10-164083 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 464 and 461,Outstanding shares 448 and 444,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q2,2010,None,None,1629000000,3479000000,1940000000,805000000,8118000000,1704000000,1229000000,1317000000,12397000000,None,3545000000,1705000000,5250000000,132000000,1158000000,None,None,None,None,None,None,None,5000000,600000000,6056000000,282000000,678000000,12397000000,294000000,5857000000,"10-Q, 0001193125-10-164083"

0001193125-10-090367 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 462 and 461,Outstanding shares 446 and 444,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2010,None,None,1844000000,3219000000,1820000000,815000000,7964000000,1436000000,1234000000,1392000000,12042000000,None,3619000000,1574000000,5193000000,131000000,1100000000,None,None,None,None,None,None,None,5000000,600000000,5887000000,145000000,471000000,12042000000,282000000,5618000000,"10-Q, 0001193125-10-090367"

0001193125-09-212134 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 449 and 445,Outstanding shares 433 and 428,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Accumulated deficit,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q3,2009,None,None,2514000000,1487000000,1617000000,671000000,6369000000,1086000000,457000000,854000000,8972000000,None,3354000000,1183000000,4537000000,116000000,734000000,None,None,None,None,None,None,None,4000000,600000000,4428000000,35000000,212000000,8972000000,286000000,3585000000,"10-Q, 0001193125-09-212134"

0001193125-09-154174 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 448 and 445,Outstanding shares 432 and 428,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Accumulated deficit,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q2,2009,None,None,1936000000,1276000000,1325000000,584000000,5304000000,981000000,451000000,821000000,7675000000,None,2508000000,1128000000,3636000000,109000000,674000000,None,None,None,None,None,None,None,4000000,600000000,4321000000,58000000,411000000,7675000000,301000000,3256000000,"10-Q, 0001193125-09-154174"

0001193125-09-085983 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 446 and 445,Outstanding shares 429 and 428,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Accumulated deficit,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2009,None,None,1701000000,1029000000,1266000000,587000000,4775000000,889000000,433000000,765000000,6980000000,None,2380000000,1030000000,3410000000,74000000,578000000,None,None,None,None,None,None,None,4000000,600000000,4210000000,143000000,553000000,6980000000,310000000,2918000000,"10-Q, 0001193125-09-085983"

0001193125-08-214483 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Current portion of long term debt,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 443 and 431,Outstanding shares 429 and 416,Treasury stock,Additional paid in capital,Accumulated other comprehensive income,Accumulated deficit,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q3,2008,None,None,1650000000,674000000,1315000000,597000000,4430000000,731000000,405000000,722000000,6566000000,None,2242000000,860000000,42000000,3144000000,393000000,502000000,None,None,None,None,None,None,None,4000000,500000000,4051000000,73000000,955000000,6566000000,472000000,2527000000,"10-Q, 0001193125-08-214483"

0001193125-08-157451 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Current portion of long term debt,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 440 and 431,Outstanding shares 426 and 416,Treasury stock,Additional paid in capital,Accumulated other comprehensive income,Accumulated deficit,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q2,2008,None,None,1548000000,832000000,1107000000,586000000,4236000000,651000000,400000000,751000000,6322000000,None,1963000000,812000000,441000000,3216000000,433000000,443000000,None,None,None,None,None,None,None,4000000,500000000,3794000000,6000000,1074000000,6322000000,447000000,2230000000,"10-Q, 0001193125-08-157451"

0001193125-08-089548 10-Q
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Current portion of long term debt,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 432 and 431,Outstanding shares 417 and 416,Treasury stock,Additional paid in capital,Accumulated other comprehensive income,Accumulated deficit,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q1,2008,None,None,1496000000,655000000,1077000000,581000000,3965000000,594000000,392000000,652000000,5883000000,None,1864000000,781000000,906000000,3551000000,467000000,395000000,None,None,None,None,None,None,None,4000000,500000000,3191000000,7000000,1232000000,5883000000,436000000,1470000000,"10-Q, 0001193125-08-089548"

0001018724-20-000004 10-K
1 duplicates  ['Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Operating leases,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term lease liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 514 and 521,Outstanding shares 491 and 498,Treasury stock,Additional paid in capital,Accumulated other comprehensive income,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2019,None,36092000000,18929000000,20497000000,20816000000,96334000000,72705000000,None,14754000000,16314000000,225248000000,None,47183000000,32439000000,8190000000,87812000000,39791000000,23414000000,12171000000,None,None,None,None,None,None,None,5000000,1837000000,33658000000,986000000,31220000000,225248000000,62060000000,"10-K, 0001018724-20-000004"

0001018724-19-000004 10-K
1 duplicates  ['Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 507 and 514,Outstanding shares 484 and 491,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2018,None,31750000000,9500000000,17174000000,16677000000,75101000000,61797000000,14548000000,11202000000,162648000000,None,38192000000,23663000000,6536000000,68391000000,23495000000,27213000000,None,None,None,None,None,None,None,5000000,1837000000,26791000000,1035000000,19625000000,162648000000,43549000000,"10-K, 0001018724-19-000004"

0001018724-18-000005 10-K
1 duplicates  ['Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 500 and 507,Outstanding shares 477 and 484,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2017,None,20522000000,10464000000,16047000000,13164000000,60197000000,48866000000,13350000000,8897000000,131310000000,None,34616000000,18170000000,5097000000,57883000000,24743000000,20975000000,None,None,None,None,None,None,None,5000000,1837000000,21389000000,484000000,8636000000,131310000000,27709000000,"10-K, 0001018724-18-000005"

0001018724-17-000011 10-K
1 duplicates  ['Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 494 and 500,Outstanding shares 471 and 477,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2017,None,19334000000,6647000000,11461000000,8339000000,45781000000,29114000000,3784000000,4723000000,83402000000,None,25309000000,13739000000,4768000000,43816000000,7694000000,12607000000,None,None,None,None,None,None,None,5000000,1837000000,17186000000,985000000,4916000000,83402000000,19285000000,"10-K, 0001018724-17-000011"

0001018724-16-000172 10-K
1 duplicates  ['Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 494 and 488,Outstanding shares 471 and 465,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2015,None,14557000000,2859000000,8299000000,5612000000,31327000000,16967000000,3319000000,2892000000,54505000000,None,16459000000,9807000000,1823000000,28089000000,8265000000,7410000000,None,None,None,None,None,None,None,5000000,1837000000,11135000000,511000000,1949000000,54505000000,10741000000,"10-K, 0001018724-16-000172"

0001018724-15-000006 10-K
1 duplicates  ['Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 488 and 483,Outstanding shares 465 and 459,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2014,None,8658000000,3789000000,7411000000,4767000000,24625000000,10949000000,2655000000,1930000000,40159000000,None,15133000000,6688000000,1159000000,22980000000,3191000000,4242000000,None,None,None,None,None,None,None,5000000,1837000000,9573000000,185000000,2190000000,40159000000,9746000000,"10-K, 0001018724-15-000006"

0001018724-14-000006 10-K
1 duplicates  ['Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 483 and 478,Outstanding shares 459 and 454,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2013,None,8084000000,3364000000,6031000000,3817000000,21296000000,7060000000,2552000000,1647000000,32555000000,None,13318000000,4892000000,792000000,19002000000,3084000000,2277000000,None,None,None,None,None,None,None,5000000,1837000000,8347000000,239000000,1916000000,32555000000,8192000000,"10-K, 0001018724-14-000006"

0001193125-13-028520 10-K
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 478 and 473,Outstanding shares 454 and 455,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2012,None,5269000000,4307000000,4992000000,2571000000,17490000000,4417000000,1955000000,1388000000,25278000000,None,11145000000,3751000000,14896000000,255000000,2370000000,None,None,None,None,None,None,None,5000000,877000000,6990000000,316000000,1955000000,25278000000,379000000,7757000000,"10-K, 0001193125-13-028520"

0001193125-12-032846 10-K
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,L I A B I L I T I E SA N DS T O C K H O L D E R SE Q U I T Y,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 473 and 468,Outstanding shares 455 and 451,Treasury stock,Additional paid in capital,Accumulated other comprehensive loss,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2011,None,3777000000,4985000000,3202000000,1587000000,13747000000,2414000000,1349000000,1265000000,18797000000,None,None,8051000000,2321000000,10372000000,1561000000,None,None,None,0,None,None,None,5000000,600000000,6325000000,190000000,1324000000,18797000000,218000000,6864000000,"10-K, 0001193125-12-032846"

0001193125-11-016253 10-K
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,L I A B I L I T I E SA N DS T O C K H O L D E R SE Q U I T Y,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares500,Issued and outstanding sharesnone,Common Stock,Authorized shares5,Issued shares468 and 461,Outstanding shares451 and 444,Treasury stock,Additional paid in capital,Accumulated other comprehensive income,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2010,None,3444000000,2922000000,2171000000,988000000,9797000000,1290000000,1234000000,1474000000,13813000000,None,None,5605000000,1759000000,7364000000,1192000000,None,None,None,None,None,None,None,5000000,600000000,5736000000,56000000,172000000,13813000000,290000000,5257000000,"10-K, 0001193125-11-016253"

0001193125-10-016098 10-K
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,L I A B I L I T I E SA N DS T O C K H O L D E R SE Q U I T Y,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares500,Issued and outstanding sharesnone,Common Stock,Authorized shares5,Issued shares461 and 445,Outstanding shares444 and 428,Treasury stock,Additional paid in capital,Accumulated other comprehensive income,Retained Earnings,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2009,None,2769000000,958000000,1399000000,827000000,6157000000,854000000,438000000,720000000,8314000000,None,None,3594000000,1152000000,4746000000,409000000,487000000,None,None,None,None,None,None,None,4000000,600000000,4121000000,123000000,730000000,8314000000,349000000,2672000000,"10-K, 0001193125-10-016098"

0001193125-09-014406 10-K
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,L I A B I L I T I E SA N DS T O C K H O L D E R SE Q U I T Y,Current liabilities,Accounts payable,Accrued expenses and other,Current portion of long term debt,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares500,Issued and outstanding sharesnone,Common Stock,Authorized shares5,Issued shares445 and 431,Outstanding shares428 and 416,Treasury stock,Additional paid in capital,Accumulated other comprehensive income,Accumulated deficit,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2008,None,2539000000,573000000,1200000000,705000000,5164000000,543000000,222000000,296000000,6485000000,None,None,2795000000,902000000,17000000,3714000000,1282000000,292000000,None,None,None,None,None,None,None,4000000,500000000,3063000000,5000000,1375000000,6485000000,407000000,1197000000,"10-K, 0001193125-09-014406"

0001193125-08-024707 10-K
2 duplicates  ['Deferred tax assets', 'Shareholder Equity']

,Quarter,Year,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Fixed assets,Goodwill,Other assets,Total assets,L I A B I L I T I E SA N DS T O C K H O L D E R SE Q U I T Y,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares500,Issued and outstanding sharesnone,Common Stock,Authorized shares5,Issued shares431 and 422,Outstanding shares416 and 414,Treasury stock,Additional paid in capital,Accumulated other comprehensive income,Accumulated deficit,Total liabilities and equity,Total Deferred tax assets,Total Shareholder Equity,Filing/Acc.No.
0,Q4,2007,None,1022000000,997000000,877000000,399000000,3373000000,457000000,195000000,139000000,4363000000,None,None,1816000000,716000000,2532000000,1247000000,153000000,None,None,None,None,None,None,None,4000000,252000000,2517000000,1000000,1837000000,4363000000,277000000,431000000,"10-K, 0001193125-08-024707"

In [5]:
abt = pd.concat(df_list, sort=False)
abt

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Property and Equipment,Operating leases,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Unearned revenue,Total current liabilities,Long term lease liabilities,Long term debt,Other long term liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 521 and 522,Outstanding shares 498 and 499,Treasury stock,Additional paid in capital,Accumulated other comprehensive income,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.,Issued shares 514 and 519,Outstanding shares 491 and 495,Accumulated other comprehensive loss,Issued shares 514 and 518,Outstanding shares 491 and 494,Issued shares 514 and 516,Outstanding shares 491 and 492,Issued shares 507 and 512,Outstanding shares 484 and 489,Issued shares 507 and 511,Outstanding shares 484 and 487,Issued shares 507 and 508,Outstanding shares 484 and 485,Issued shares 500 and 505,Outstanding shares 477 and 482,Issued shares 500 and 504,Outstanding shares 477 and 480,Issued shares 500 and 501,Outstanding shares 477 and 478,Issued shares 498 and 494,Outstanding shares 475 and 471,Issued shares 497 and 494,Outstanding shares 474 and 471,Issued shares 495 and 494,Outstanding shares 472 and 471,Issued shares 492 and 488,Outstanding shares 469 and 465,Issued shares 491 and 488,Outstanding shares 468 and 465,Issued shares 489 and 488,Outstanding shares 466 and 465,Issued shares 487 and 483,Outstanding shares 463 and 459,Issued shares 486 and 483,Outstanding shares 462 and 459,Issued shares 484 and 483,Outstanding shares 460 and 459,Issued shares 481 and 478,Outstanding shares 458 and 454,Total Deferred tax assets,Issued shares 480 and 478,Outstanding shares 457 and 454,Issued shares 479 and 478,Outstanding shares 455 and 454,Fixed assets,Long term liabilities,Issued shares 476 and 473,Outstanding shares 453 and 455,Outstanding shares 452 and 455,Issued shares 474 and 473,Outstanding shares 450 and 455,Issued shares 471 and 468,Outstanding shares 455 and 451,Outstanding shares 454 and 451,Issued shares 469 and 468,Outstanding shares 452 and 451,Issued shares 466 and 461,Outstanding shares 449 and 444,Issued shares 464 and 461,Outstanding shares 448 and 444,Issued shares 462 and 461,Outstanding shares 446 and 444,Issued shares 449 and 445,Outstanding shares 433 and 428,Accumulated deficit,Issued shares 448 and 445,Outstanding shares 432 and 428,Issued shares 446 and 445,Outstanding shares 429 and 428,Current portion of long term debt,Issued shares 443 and 431,Outstanding shares 429 and 416,Issued shares 440 and 431,Outstanding shares 426 and 416,Issued shares 432 and 431,Outstanding shares 417 and 416,Issued shares 514 and 521,Outstanding shares 491 and 498,Issued shares 507 and 514,Outstanding shares 484 and 491,Issued shares 500 and 507,Outstanding shares 477 and 484,Issued shares 494 and 500,Outstanding shares 471 and 477,Issued shares 494 and 488,Outstanding shares 471 and 465,Issued shares 488 and 483,Outstanding shares 465 and 459,Issued shares 483 and 478,Outstanding shares 459 and 454,Issued shares 478 and 473,Outstanding shares 454 and 455,L I A B I L I T I E SA N DS T O C K H O L D E R SE Q U I T Y,Issued shares 473 and 468,Authorized shares500,Issued and outstanding sharesnone,Authorized shares5,Issued shares468 and 461,Outstanding shares451 and 444,Issued shares461 and 445,Outstanding shares444 and 428,Issued shares445 and 431,Outstanding shares428 and 416,Issued shares431 and 422,Outstanding shares416 and 414
0,Q1,2020,None,None,27201000000,22091000000,18857000000,17836000000,85985000000,77779000000,26279000000,14739000000,16456000000,221238000000,None,40056000000,30791000000,8864000000,79711000000,40300000000,23437000000,12518000000,None,None,None,None,None,None,None,5000000,1837000000,35412000000,2063000000,33755000000,221238000000,65272000000,"10-Q, 0001018724-20-000010",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q3,2019,None,None,23255000000,20146000000,18766000000,16887000000,79054000000,67662000000,None,14734000000,14535000000,199099000000,None,35794000000,28961000000,7381000000,72136000000,37058000000,22472000000,10925000000,None,None,None,None,None,None,NaN,NaN,1837000000,31817000000,NaN,27952000000,199099000000,56508000000,"10-Q, 0001018724-19-000089",None,5000000,1429000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q2,2019,None,None,22616000000,18847000000,18580000000,16747000000,76790000000,64723000000,None,14727000000,13462000000,191351000000,None,36063000000,26140000000,7475000000,69678000000,35134000000,23329000000,10149000000,None,None,None,None,None,None,NaN,NaN,1837000000,30035000000,NaN,25818000000,191351000000,53061000000,"10-Q, 0001018724-19-000071",NaN,NaN,960000000,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q1,2019,None,None,23115000000,13905000000,16432000000,15979000000,69431000000,61048000000,None,14708000000,12783000000,178102000000,None,31809000000,24588000000,7298000000,63695000000,33275000000,23322000000,9400000000,None,None,None,None,None,None,NaN,NaN,1837000000,28059000000,NaN,23193000000,178102000000,48410000000,"10-Q, 0001018724-19-000043",NaN,NaN,1010000000,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q3,2018,None,None,20425000000,9340000000,15862000000,14258000000,59885000000,58019000000,NaN,14553000000,11238000000,143695000000,None,30904000000,18420000000,6000000000,55324000000,NaN,24684000000,24562000000,None,None,None,None,None,None,NaN,NaN,1837000000,25375000000,NaN,16616000000,143695000000,39125000000,"10-Q, 0001018724-18-000159",NaN,NaN,1034000000,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q2,2018,None,None,19823000000,7227000000,14824000000,12607000000,54481000000,54768000000,NaN,13944000000,10907000000,134100000000,None,27657000000,17140000000,6004000000,50801000000,NaN,24638000000,23666000000,None,None,None,None,None,None,NaN,NaN,1837000000,24028000000,NaN,13733000000,134100000000,34995000000,"10-Q, 0001018724-18-000108",NaN,NaN,934000000,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q1,2018,None,None,16676000000,8287000000,13840000000,12026000000,50829000000,52331000000,NaN,13388000000,9814000000,126362000000,None,25172000000,16691000000,6182000000,48045000000,NaN,24640000000,22214000000,None,None,None,None,None,None,NaN,NaN,1837000000,22563000000,NaN,11199000000,126362000000,31463000000,"10-Q, 0001018724-18-000072",NaN,NaN,467000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q3,2017,None,None,12767000000,11543000000,13711000000,10557000000,48578000000,45335000000,NaN,13271000000,8083000000,115267000000,None,26075000000,15844000000,5153000000,47072000000,NaN,24710000000,18827000000,None,None,None,None,None,None,NaN,NaN,1837000000,20212000000,NaN,6779000000,115267000000,24658000000,"10-Q, 0001018724-17-000135",NaN,NaN,501000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q2,2017,None,None,13203000000,8248000000,11510000000,8046000000,41007000000,37083000000,NaN,4254000000,5437000000,87781000000,None,21439000000,14016000000,5065000000,40520000000,NaN,7683000000,16364000000,None,None,None,None,None,None,NaN,NaN,1837000000,19129000000,NaN,6524000000,87781000000,23214000000,"10-Q, 0001018724-17-000100",NaN,NaN,607000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q1,2017,None,None,15440000000,6091000000,10600000000,7329000000,39460000000,32632000000,NaN,3823000000,5054000000,80969000000,None,18891000000,13054000000,5454000000,37399000000,NaN,7691000000,14205000000,None,None,None,None,None,None,NaN,NaN,1837000000,17976000000,NaN,6327000000,80969000000,21674000000,"10-Q, 0001018724-17-000051",NaN,NaN,797000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q3,2016,None,None,13656000000,4691000000,10696000000,6566000000,35609000000,27177000000,NaN,3815000000,4296000000,70897000000,None,18801000000,10497000000,4200000000,33498000000,NaN,8205000000,11412000000,None,None,None,None,None,None,NaN,NaN,1837000000,15968000000,NaN,4167000000,70897000000,17782000000,"10-Q, 0001018724-16-000324",NaN,NaN,521000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q2,2016,None,None,12521000000,4019000000,9588000000,6092000000,32220000000,25190000000,NaN,3774000000,3892000000,65076000000,None,16123000000,9613000000,3851000000,29587000000,NaN,8212000000,10739000000,None,None,None,None,None,None,NaN,NaN,1837000000,15026000000,NaN,3915000000,65076000000,16538000000,"10-Q, 0001018724-16-000286",NaN,NaN,571000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q1,2016,None,None,12470000000,3389000000,9582000000,5072000000,30513000000,23308000000,NaN,3785000000,3522000000,61128000000,None,14990000000,9431000000,3766000000,28187000000,NaN,8219000000,9966000000,None,None,None,None,None,None,NaN,NaN,1837000000,14144000000,NaN,3058000000,61128000000,14756000000,"10-Q, 0001018724-16-000227",NaN,NaN,614000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q3,2015,None,None,10709000000,3719000000,8981000000,5440000000,28849000000,20636000000,NaN,3529000000,3216000000,56230000000,None,14437000000,9157000000,3063000000,26657000000,NaN,8243000000,8900000000,None,None,None,None,None,None,NaN,NaN,1837000000,12874000000,NaN,2063000000,56230000000,12430000000,"10-Q, 0001018724-15-000126",NaN,NaN,675000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q2,2015,None,None,10269000000,3732000000,7470000000,4920000000,26391000000,19479000000,NaN,3523000000,3047000000,52440000000,None,12391000000,8959000000,2562000000,23912000000,NaN,8250000000,8510000000,None,None,None,None,None,None,NaN,NaN,1837000000,12233000000,NaN,1984000000,52440000000,11768000000,"10-Q, 0001018724-15-000087",NaN,NaN,617000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q1,2015,None,None,10237000000,3544000000,7369000000,4772000000,25922000000,17736000000,NaN,3491000000,2926000000,50075000000,None,11917000000,8840000000,2420000000,23177000000,NaN,8257000000,7768000000,None,None,None,None,None,None,NaN,NaN,1837000000,11565000000,NaN,1892000000,50075000000,10873000000,"10-Q, 0001018724-15-000038",NaN,NaN,752000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q3,2014,None,None,5258000000,1625000000,7316000000,4373000000,18572000000,15702000000,NaN,3332000000,2813000000,40419000000,None,11811000000,7217000000,1814000000,20842000000,NaN,3099000000,6142000000,None,None,None,None,None,None,NaN,NaN,1837000000,10827000000,NaN,1735000000,40419000000,10336000000,"10-Q, 0001018724-14-000055",NaN,NaN,394000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q2,2014,None,None,5057000000,2929000000,6644000000,4125000000,18755000000,14089000000,NaN,2677000000,2377000000,37898000000,None,10457000000,6688000000,1606000000,18751000000,NaN,3119000000,5426000000,None,None,None,None,None,None,NaN,NaN,1837000000,10405000000,NaN,2172000000,37898000000,10602000000,"10-Q, 0001018724-14-000025",NaN,NaN,143000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q1,2014,None,None,5074000000,3592000000,6716000000,3945000000,19327000000,12267000000,NaN,2653000000,2117000000,36364000000,None,10590000000,6251000000,1516000000,18357000000,NaN,3147000000,4532000000,None,None,None,None,None,None,NaN,NaN,1837000000,10019000000,NaN,2298000000,36364000000,10328000000,"10-Q, 0001018724-14-000014",NaN,NaN,157000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q3,2013,None,None,3872000000,3817000000,6068000000,3057000000,17334000000,9991000000,NaN,2635000000,1773000000,31861000000,None,10037000000,6098000000,NaN,16135000000,NaN,3043000000,3596000000,None,None,None,None,None,None,NaN,NaN,1837000000,9175000000,NaN,1950000000,31861000000,9087000000,"10-Q, 0001445305-13-002495",NaN,NaN,206000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5000000,648000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Q2,2013,None,None,3704000000,3759000000,5420000000,2861000000,16285000000,8789000000,NaN,2614000000,1807000000,29623000000,None,8990000000,5745000000,NaN,14735000000,NaN,3042000000,3113000000,None,None,None,None,None,None,NaN,NaN,1837000000,8893000000,NaN,1991000000,29623000000,8733000000,"10-Q, 0001193125-13-303204",NaN,NaN,319000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,669000000.0,None,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
abt.reset_index(drop=True, inplace=True)

In [7]:
# Q4 2016 was originally 2017. 
abt.iloc[40,1] = '2016'

In [8]:
abt.iloc[40,1]

'2016'

In [9]:
# All column names are unique, the duplicate column function did its job.
original_col = list(abt.columns)
len(original_col) == len(set(original_col))

True

In [10]:
original_col

['Quarter',
 'Year',
 'ASSETS',
 'Current assets',
 'Cash',
 'Marketable securities',
 'Inventory',
 'Accounts Receivable',
 'Total current assets',
 'Property and Equipment',
 'Operating leases',
 'Goodwill',
 'Other assets',
 'Total assets',
 'Current liabilities',
 'Accounts payable',
 'Accrued expenses and other',
 'Unearned revenue',
 'Total current liabilities',
 'Long term lease liabilities',
 'Long term debt',
 'Other long term liabilities',
 'Commitments and contingencies',
 'Preferred Stock',
 'Authorized shares  500',
 'Issued and outstanding shares  none',
 'Common Stock',
 'Authorized shares  5',
 'Issued shares  521 and 522',
 'Outstanding shares  498 and 499',
 'Treasury stock',
 'Additional paid in capital',
 'Accumulated other comprehensive income',
 'Retained Earnings',
 'Total liabilities and equity',
 'Total Shareholder Equity',
 'Filing/Acc.No.',
 'Issued shares  514 and 519',
 'Outstanding shares  491 and 495',
 'Accumulated other comprehensive loss',
 'Issued shares  514 and 518',
 'Outstanding shares  491 and 494',
 'Issued shares  514 and 516',
 'Outstanding shares  491 and 492',
 'Issued shares  507 and 512',
 'Outstanding shares  484 and 489',
 'Issued shares  507 and 511',
 'Outstanding shares  484 and 487',
 'Issued shares  507 and 508',
 'Outstanding shares  484 and 485',
 'Issued shares  500 and 505',
 'Outstanding shares  477 and 482',
 'Issued shares  500 and 504',
 'Outstanding shares  477 and 480',
 'Issued shares  500 and 501',
 'Outstanding shares  477 and 478',
 'Issued shares  498 and 494',
 'Outstanding shares  475 and 471',
 'Issued shares  497 and 494',
 'Outstanding shares  474 and 471',
 'Issued shares  495 and 494',
 'Outstanding shares  472 and 471',
 'Issued shares  492 and 488',
 'Outstanding shares  469 and 465',
 'Issued shares  491 and 488',
 'Outstanding shares  468 and 465',
 'Issued shares  489 and 488',
 'Outstanding shares  466 and 465',
 'Issued shares  487 and 483',
 'Outstanding shares  463 and 459',
 'Issued shares  486 and 483',
 'Outstanding shares  462 and 459',
 'Issued shares  484 and 483',
 'Outstanding shares  460 and 459',
 'Issued shares  481 and 478',
 'Outstanding shares  458 and 454',
 'Total Deferred tax assets',
 'Issued shares  480 and 478',
 'Outstanding shares  457 and 454',
 'Issued shares  479 and 478',
 'Outstanding shares  455 and 454',
 'Fixed assets',
 'Long term liabilities',
 'Issued shares  476 and 473',
 'Outstanding shares  453 and 455',
 'Outstanding shares  452 and 455',
 'Issued shares  474 and 473',
 'Outstanding shares  450 and 455',
 'Issued shares  471 and 468',
 'Outstanding shares  455 and 451',
 'Outstanding shares  454 and 451',
 'Issued shares  469 and 468',
 'Outstanding shares  452 and 451',
 'Issued shares  466 and 461',
 'Outstanding shares  449 and 444',
 'Issued shares  464 and 461',
 'Outstanding shares  448 and 444',
 'Issued shares  462 and 461',
 'Outstanding shares  446 and 444',
 'Issued shares  449 and 445',
 'Outstanding shares  433 and 428',
 'Accumulated deficit',
 'Issued shares  448 and 445',
 'Outstanding shares  432 and 428',
 'Issued shares  446 and 445',
 'Outstanding shares  429 and 428',
 'Current portion of long term debt',
 'Issued shares  443 and 431',
 'Outstanding shares  429 and 416',
 'Issued shares  440 and 431',
 'Outstanding shares  426 and 416',
 'Issued shares  432 and 431',
 'Outstanding shares  417 and 416',
 'Issued shares  514 and 521',
 'Outstanding shares  491 and 498',
 'Issued shares  507 and 514',
 'Outstanding shares  484 and 491',
 'Issued shares  500 and 507',
 'Outstanding shares  477 and 484',
 'Issued shares  494 and 500',
 'Outstanding shares  471 and 477',
 'Issued shares  494 and 488',
 'Outstanding shares  471 and 465',
 'Issued shares  488 and 483',
 'Outstanding shares  465 and 459',
 'Issued shares  483 and 478',
 'Outstanding shares  459 and 454',
 'Issued shares  478 and 473',
 'Outstanding shares  454 and 455',
 'L I A B I L I T I E SA N DS T O C K H O L D E R SE Q U I T Y',
 'Issued shares  473 and 468',
 'Authorized shares500',
 'Issued and outstanding sharesnone',
 'Authorized shares5',
 'Issued shares468 and 461',
 'Outstanding shares451 and 444',
 'Issued shares461 and 445',
 'Outstanding shares444 and 428',
 'Issued shares445 and 431',
 'Outstanding shares428 and 416',
 'Issued shares431 and 422',
 'Outstanding shares416 and 414']

In [11]:
new_col =['Quarter',
 'Year',
 'Cash',
 'Marketable securities',
 'Inventory',
 'Accounts Receivable',
 'Total current assets',
 'Property and Equipment',
 'Goodwill',
 'Other assets',
 'Total assets',
 'Accounts payable',
 'Accrued expenses and other',
 'Unearned revenue',
 'Total current liabilities',
 'Long term debt',
 'Other long term liabilities',
 'Treasury stock',
 'Additional paid in capital',
 'Retained Earnings',
 'Total liabilities and equity',
 'Total Shareholder Equity',
 'Filing/Acc.No.',
 'Accumulated other comprehensive loss']

In [13]:
# Dont execute, testing
abt.drop([ 'Current portion of long term debt'], axis=1, inplace=True)
abt['Total current liabilities']

In [14]:
Non_current_liabilities = ['Other long term liabilities', "Long term liabilities", "Long term debt", 'Long term lease liabilities' ]
abt['Total non current liabilities'] = abt[Non_current_liabilities].sum(axis=1)
abt.drop(Non_current_liabilities, axis=1, inplace=True)

In [15]:
abt['Total Property and Equipment'] = abt[[ 'Fixed assets', "Property and Equipment"]].sum(axis=1)
abt.drop([ 'Fixed assets', "Property and Equipment"], axis=1, inplace=True)

In [16]:
abt['Deferred Revenue'] = abt[["Total Deferred tax assets", "Unearned revenue"]].sum(axis=1)
abt.drop(["Total Deferred tax assets", "Unearned revenue"], axis=1, inplace=True)

In [17]:
abt['Accumulated comprehensive income'] = abt[["Accumulated other comprehensive income" , 'Accumulated other comprehensive loss']].sum(axis=1)
abt.drop(["Accumulated other comprehensive income" , 'Accumulated other comprehensive loss'], axis=1, inplace=True)

In [18]:
abt["Retained Earnings"] = abt[["Accumulated deficit", "Retained Earnings" ]].sum(axis=1)

In [19]:
abt.drop(["Accumulated deficit"], axis=1, inplace=True)

In [20]:
abt['Common Stock'] = abt[['Outstanding shares  498 and 499', 'Outstanding shares  491 and 495', 'Outstanding shares  491 and 494', 'Outstanding shares  491 and 492', 'Outstanding shares  484 and 489', 'Outstanding shares  484 and 487', 'Outstanding shares  484 and 485', 'Outstanding shares  477 and 482', 'Outstanding shares  477 and 480', 'Outstanding shares  477 and 478', 'Outstanding shares  475 and 471', 'Outstanding shares  474 and 471', 'Outstanding shares  472 and 471', 'Outstanding shares  469 and 465', 'Outstanding shares  468 and 465', 'Outstanding shares  466 and 465', 'Outstanding shares  463 and 459', 'Outstanding shares  462 and 459', 'Outstanding shares  460 and 459', 'Outstanding shares  458 and 454', 'Outstanding shares  457 and 454', 'Outstanding shares  455 and 454', 'Outstanding shares  453 and 455', 'Outstanding shares  452 and 455', 'Outstanding shares  450 and 455', 'Outstanding shares  455 and 451', 'Outstanding shares  454 and 451', 'Outstanding shares  452 and 451', 'Outstanding shares  449 and 444', 'Outstanding shares  448 and 444', 'Outstanding shares  446 and 444', 'Outstanding shares  433 and 428', 'Outstanding shares  432 and 428', 'Outstanding shares  429 and 428', 'Outstanding shares  429 and 416', 'Outstanding shares  426 and 416', 'Outstanding shares  417 and 416', 'Outstanding shares  491 and 498', 'Outstanding shares  484 and 491', 'Outstanding shares  477 and 484', 'Outstanding shares  471 and 477', 'Outstanding shares  471 and 465', 'Outstanding shares  465 and 459', 'Outstanding shares  459 and 454', 'Outstanding shares  454 and 455', 'Outstanding shares451 and 444', 'Outstanding shares444 and 428', 'Outstanding shares428 and 416', 'Outstanding shares416 and 414']].sum(axis=1)
abt.drop(['Outstanding shares  498 and 499', 'Outstanding shares  491 and 495', 'Outstanding shares  491 and 494', 'Outstanding shares  491 and 492', 'Outstanding shares  484 and 489', 'Outstanding shares  484 and 487', 'Outstanding shares  484 and 485', 'Outstanding shares  477 and 482', 'Outstanding shares  477 and 480', 'Outstanding shares  477 and 478', 'Outstanding shares  475 and 471', 'Outstanding shares  474 and 471', 'Outstanding shares  472 and 471', 'Outstanding shares  469 and 465', 'Outstanding shares  468 and 465', 'Outstanding shares  466 and 465', 'Outstanding shares  463 and 459', 'Outstanding shares  462 and 459', 'Outstanding shares  460 and 459', 'Outstanding shares  458 and 454', 'Outstanding shares  457 and 454', 'Outstanding shares  455 and 454', 'Outstanding shares  453 and 455', 'Outstanding shares  452 and 455', 'Outstanding shares  450 and 455', 'Outstanding shares  455 and 451', 'Outstanding shares  454 and 451', 'Outstanding shares  452 and 451', 'Outstanding shares  449 and 444', 'Outstanding shares  448 and 444', 'Outstanding shares  446 and 444', 'Outstanding shares  433 and 428', 'Outstanding shares  432 and 428', 'Outstanding shares  429 and 428', 'Outstanding shares  429 and 416', 'Outstanding shares  426 and 416', 'Outstanding shares  417 and 416', 'Outstanding shares  491 and 498', 'Outstanding shares  484 and 491', 'Outstanding shares  477 and 484', 'Outstanding shares  471 and 477', 'Outstanding shares  471 and 465', 'Outstanding shares  465 and 459', 'Outstanding shares  459 and 454', 'Outstanding shares  454 and 455', 'Outstanding shares451 and 444', 'Outstanding shares444 and 428', 'Outstanding shares428 and 416', 'Outstanding shares416 and 414'], axis=1, inplace=True)

In [21]:
# What is the percentage of nulls in a given column.
count = 1
shares = []
for columns in abt:
    
    ratio = abt[columns].notna().astype(int).mean()
    if  1 > ratio > 0.01:
        print(f' {count}.  "{columns}" ')
        print( ratio )
        print()
        count+=1
        shares.append(columns)
        
print('Length of Shares: ',len(shares) )   
print( shares )

 1.  "Operating leases"
0.02

 2.  "Issued and outstanding shares  none"
0.04

Length of Shares:  2
['Operating leases', 'Issued and outstanding shares  none']

In [22]:
abt[['Operating leases', 'Issued and outstanding shares  none']]

   Operating leases Issued and outstanding shares  none
0       26279000000                                None
1              None                                None
2              None                                None
3              None                                None
4               NaN                                None
5               NaN                                None
6               NaN                                None
7               NaN                                None
8               NaN                                None
9               NaN                                None
10              NaN                                None
11              NaN                                None
12              NaN                                None
13              NaN                                None
14              NaN                                None
15              NaN                                None
16              NaN                                None
17              NaN                                None
18              NaN                                None
19              NaN                                None
20              NaN                                None
21              NaN                                None
22              NaN                                None
23              NaN                                None
24              NaN                                None
25              NaN                                   0
26              NaN                                None
27              NaN                                None
28              NaN                                None
29              NaN                                None
30              NaN                                None
31              NaN                                None
32              NaN                                None
33              NaN                                None
34              NaN                                None
35              NaN                                None
36              NaN                                None
37             None                                None
38              NaN                                None
39              NaN                                None
40              NaN                                None
41              NaN                                None
42              NaN                                None
43              NaN                                None
44              NaN                                None
45              NaN                                   0
46              NaN                                 NaN
47              NaN                                 NaN
48              NaN                                 NaN
49              NaN                                 NaN

In [24]:
abt

,Quarter,Year,ASSETS,Current assets,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Operating leases,Goodwill,Other assets,Total assets,Current liabilities,Accounts payable,Accrued expenses and other,Total current liabilities,Commitments and contingencies,Preferred Stock,Authorized shares 500,Issued and outstanding shares none,Common Stock,Authorized shares 5,Issued shares 521 and 522,Treasury stock,Additional paid in capital,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.,Issued shares 514 and 519,Issued shares 514 and 518,Issued shares 514 and 516,Issued shares 507 and 512,Issued shares 507 and 511,Issued shares 507 and 508,Issued shares 500 and 505,Issued shares 500 and 504,Issued shares 500 and 501,Issued shares 498 and 494,Issued shares 497 and 494,Issued shares 495 and 494,Issued shares 492 and 488,Issued shares 491 and 488,Issued shares 489 and 488,Issued shares 487 and 483,Issued shares 486 and 483,Issued shares 484 and 483,Issued shares 481 and 478,Issued shares 480 and 478,Issued shares 479 and 478,Issued shares 476 and 473,Issued shares 474 and 473,Issued shares 471 and 468,Issued shares 469 and 468,Issued shares 466 and 461,Issued shares 464 and 461,Issued shares 462 and 461,Issued shares 449 and 445,Issued shares 448 and 445,Issued shares 446 and 445,Issued shares 443 and 431,Issued shares 440 and 431,Issued shares 432 and 431,Issued shares 514 and 521,Issued shares 507 and 514,Issued shares 500 and 507,Issued shares 494 and 500,Issued shares 494 and 488,Issued shares 488 and 483,Issued shares 483 and 478,Issued shares 478 and 473,L I A B I L I T I E SA N DS T O C K H O L D E R SE Q U I T Y,Issued shares 473 and 468,Authorized shares500,Issued and outstanding sharesnone,Authorized shares5,Issued shares468 and 461,Issued shares461 and 445,Issued shares445 and 431,Issued shares431 and 422,Total non current liabilities,Total Property and Equipment,Deferred Revenue,Accumulated comprehensive income
0,Q1,2020,None,None,27201000000,22091000000,18857000000,17836000000,85985000000,26279000000,14739000000,16456000000,221238000000,None,40056000000,30791000000,79711000000,None,None,None,None,5000000.0,None,None,1837000000,35412000000,33755000000.0,221238000000,65272000000,"10-Q, 0001018724-20-000010",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76255000000.0,77779000000.0,8864000000.0,2063000000.0
1,Q3,2019,None,None,23255000000,20146000000,18766000000,16887000000,79054000000,None,14734000000,14535000000,199099000000,None,35794000000,28961000000,72136000000,None,None,None,None,5000000.0,None,NaN,1837000000,31817000000,27952000000.0,199099000000,56508000000,"10-Q, 0001018724-19-000089",None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70455000000.0,67662000000.0,7381000000.0,1429000000.0
2,Q2,2019,None,None,22616000000,18847000000,18580000000,16747000000,76790000000,None,14727000000,13462000000,191351000000,None,36063000000,26140000000,69678000000,None,None,None,None,5000000.0,None,NaN,1837000000,30035000000,25818000000.0,191351000000,53061000000,"10-Q, 0001018724-19-000071",NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68612000000.0,64723000000.0,7475000000.0,960000000.0
3,Q1,2019,None,None,23115000000,13905000000,16432000000,15979000000,69431000000,None,14708000000,12783000000,178102000000,None,31809000000,24588000000,63695000000,None,None,None,None,5000000.0,None,NaN,1837000000,28059000000,23193000000.0,178102000000,48410000000,"10-Q, 0001018724-19-000043",NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65997000000.0,61048000000.0,7298000000.0,1010000000.0
4,Q3,2018,None,None,20425000000,9340000000,15862000000,14258000000,59885000000,NaN,14553000000,11238000000,143695000000,None,30904000000,18420000000,55324000000,None,None,None,None,5000000.0,None,NaN,1837000000,25375000000,16616000000.0,143695000000,39125000000,"10-Q, 0001018724-18-000159",NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49246000000.0,58019000000.0,6000000000.0,1034000000.0
5,Q2,2018,None,None,19823000000,7227000000,14824000000,12607000000,54481000000,NaN,13944000000,10907000000,134100000000,None,27657000000,17140000000,50801000000,None,None,None,None,5000000.0,None,NaN,1837000000,24028000000,13733000000.0,134100000000,34995000000,"10-Q, 0001018724-18-000108",NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48304000000.0,54768000000.0,6004000000.0,934000000.0
6,Q1,2018,None,None,16676000000,8287000000,13840000000,12026000000,50829000000,NaN,13388000000,9814000000,126362000000,None,25172000000,16691000000,48045000000,None,None,None,None,5000000.0,None,NaN,1837000000,22563000000,11199000000.0,126362000000,31463000000,"10-Q, 0001018724-18-000072",NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46854000000.0,52331000000.0,6182000000.0,467000000.0
7,Q3,2017,None,None,12767000000,11543000000,13711000000,10557000000,48578000000,NaN,13271000000,8083000000,115267000000,None,26075000000,15844000000,47072000000,None,None,None,None,5000000.0,None,NaN,1837000000,20212000000,6779000000.0,115267000000,24658000000,"10-Q, 0001018724-17-000135",NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43537000000.0,45335000000.0,5153000000.0,501000000.0
8,Q2,2017,None,None,13203000000,8248000000,11510000000,8046000000,41007000000,NaN,4254000000,5437000000,87781000000,None,21439000000,14016000000,40520000000,None,None,None,None,5000000.0,None,NaN,1837000000,19129000000,6524000000.0,87781000000,23214000000,"10-Q, 0001018724-17-000100",NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24047000000.0,37083000000.0,5065000000.0,607000000.0
9,Q1,2017,None,None,15440000000,6091000000,10600000000,7329000000,39460000000,NaN,3823000000,5054000000,80969000000,None,18891000000,13054000000,37399000000,None,None,None,None,5000000.0,None,NaN,1837000000,17976000000,6327000000.0,80969000000,21674000000,"10-Q, 0001018724-17-000051",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21896000000.0,32632000000.0,5454000000.0,797000000.0
10,Q3,2016,None,None,13656000000,4691000000,10696000000,6566000000,35609000000,NaN,3815000000,4296000000,70897000000,None,18801000000,10497000000,33498000000,None,None,None,None,5000000.0,None,NaN,1837000000,15968000000,4167000000.0,70897000000,17782000000,"10-Q, 0001018724-16-000324",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19617000000.0,27177000000.0,4200000000.0,521000000.0
11,Q2,2016,None,None,12521000000,4019000000,9588000000,6092000000,32220000000,NaN,3774000000,3892000000,65076000000,None,16123000000,9613000000,29587000000,None,None,None,None,5000000.0,None,NaN,1837000000,15026000000,3915000000.0,65076000000,16538000000,"10-Q, 0001018724-16-000286",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18951000000.0,25190000000.0,3851000000.0,571000000.0
12,Q1,2016,None,None,12470000000,3389000000,9582000000,5072000000,30513000000,NaN,3785000000,3522000000,61128000000,None,14990000000,9431000000,28187000000,None,None,None,None,5000000.0,None,NaN,1837000000,14144000000,3058000000.0,61128000000,14756000000,"10-Q, 0001018724-16-000227",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18185000000.0,23308000000.0,3766000000.0,614000000.0
13,Q3,2015,None,None,10709000000,3719000000,8981000000,5440000000,28849000000,NaN,3529000000,3216000000,56230000000,None,14437000000,9157000000,26657000000,None,None,None,None,5000000.0,None,NaN,1837000000,12874000000,2063000000.0,56230000000,12430000000,"10-Q, 0001018724-15-000126",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17143000000.0,20636000000.0,3063000000.0,675000000.0
14,Q2,2015,None,None,10269000000,3732000000,7470000000,4920000000,26391000000,NaN,3523000000,3047000000,52440000000,None,12391000000,8959000000,23912000000,None,None,None,None,5000000.0,None,NaN,1837000000,12233000000,1984000000.0,52440000000,11768000000,"10-Q, 0001018724-15-000087",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16760000000.0,19479000000.0,2562000000.0,617000000.0
15,Q1,2015,None,None,10237000000,3544000000,7369000000,4772000000,25922000000,NaN,3491000000,2926000000,50075000000,None,11917000000,8840000000,23177000000,None,None,None,None,5000000.0,None,NaN,1837000000,11565000000,1892000000.0,50075000000,10873000000,"10-Q, 0001018724-15-000038",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16025000000.0,17736000000.0,2420000000.0,752000000.0
16,Q3,2014,None,None,5258000000,1625000000,7316000000,4373000000,18572000000,NaN,3332000000,2813000000,40419000000,None,11811000000,7217000000,20842000000,None,None,None,None,5000000.0,None,NaN,1837000000,10827000000,1735000000.0,40419000000,10336000000,"10-Q, 0001018724-14-000055",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9241000000.0,15702000000.0,1814000000.0,394000000.0
17,Q2,2014,None,None,5057000000,2929000000,6644000000,4125000000,18755000000,NaN,2677000000,2377000000,37898000000,None,10457000000,6688000000,18751000000,None,None,None,None,5000000.0,None,NaN,1837000000,10405000000,2172000000.0,37898000000,10602000000,"10-Q, 0001018724-14-000025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8545000000.0,14089000000.0,1606000000.0,143000000.0
18,Q1,2014,None,None,5074000000,3592000000,6716000000,3945000000,19327000000,NaN,2653000000,2117000000,36364000000,None,10590000000,6251000000,18357000000,None,None,None,None,5000000.0,None,NaN,1837000000,10019000000,2298000000.0,36364000000,10328000000,"10-Q, 0001018724-14-000014",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7679000000.0,12267000000.0,1516000000.0,157000000.0
19,Q3,2013,None,None,3872000000,3817000000,6068000000,3057000000,17334000000,NaN,2635000000,1773000000,31861000000,None,10037000000,6098000000,16135000000,None,None,None,None,5000000.0,None,NaN,1837000000,9175000000,1950000000.0,31861000000,9087000000,"10-Q, 0001445305-13-002495",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6639000000.0,9991000000.0,648000000.0,206000000.0
20,Q2,2013,None,None,3704000000,3759000000,5420000000,2861000000,16285000000,NaN,2614000000,1807000000,29623000000,None,8990000000,5745000000,14735000000,None,None,None,None,5000000.0,None,NaN,1837000000,8893000000,1991000000.0,29623000000,8733000000,"10-Q, 0001193125-13-303204",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6155000000.0,8789000000.0,669000000.0,319000000.0
21,Q1,2013,None,None,4481000000,3414000000,5395000000,2516000000,16313000000,NaN,2535000000,1732000000,28377000000,None,8916000000,5416000000,14332000000,None,None,None,None,5000000.0,None,NaN,1837000000,8585000000,1998000000.0,28377000000,8432000000,"10-Q, 0001193125-13-174667",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5613000000.0,7674000000.0,630000000.0,319000000.0
22,Q3,2012,None,None,2980000000,2268000000,5065000000,2392000000,13118000000,NaN,2540000000,1476000000,22834000000,None,8369000000,4236000000,12605000000,None,None,None,None,5000000.0,None,NaN,1837000000,7863000000,1818000000.0,22834000000,7553000000,"10-Q, 0001193125-12-436012",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2676000000.0,5662000000.0,451000000.0,296000000.0
23,Q2,2012,None,None,2335000000,2635000000,4380000000,2035000000,11793000000,NaN,2521000000,1585000000,21022000000,None,7072000000,3892000000,10964000000,None,None,None,None,5000000.0,None,NaN,1837000000,7573000000,2092000000.0,21022000000,7505000000,"10-Q, 0001193125-12-317409",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2553000000.0,5097000000.0,434000000.0,328000000.0
24,Q1,2012,None,None,2288000000,3427000000,4255000000,1813000000,12154000000,NaN,1970000000,1535000000,20339000000,None,6886000000,3602000000,10488000000,None,None,None,None,5000000.0,None,NaN,1837000000,7192000000,2085000000.0,20339000000,7271000000,"10-Q, 0001193125-12-187203",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2580000000.0,4653000000.0,398000000.0,174000000.0
25,Q3,2011,None,None,2823000000,3503000000,3770000000,1496000000,11904000000,NaN,1934000000,1190000000,19054000000,None,6552000000,2426000000,8978000000,None,None,None,0,5000000.0,None,NaN,600000000,6824000000,1778000000.0,19054000000,7766000000,"10-Q, 0001193125-11-280739",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2310000000.0,3999000000.0,339000000.0,241000000.0
26,Q2,2011,None,None,2047000000,4308000000,3229000000,1438000000,11279000000,NaN,1909000000,1253000000,17941000000,None,5721000000,2324000000,8045000000,None,None,None,None,5000000.0,None,NaN,600000000,6675000000,1715000000.0,17941000000,7765000000,"10-Q, 0001193125-11-197823",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2131000000.0,3470000000.0,287000000.0,30000000.0
27,Q1,2011,None,None,2641000000,4240000000,2888000000,1304000000,11288000000,NaN,1513000000,1151000000,16882000000,None,5540000000,2190000000,7730000000,None,None,None,None,5000000.0,None,NaN,600000000,6483000000,1525000000.0,16882000000,7347000000,"10-Q, 0001193125-11-110197",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1805000000.0,2902000000.0,243000000.0,66000000.0
28,Q3,2010,None,None,1539000000,4346000000,2515000000,959000000,9559000000,NaN,1277000000,1184000000,14162000000,None,4614000000,1761000000,6375000000,None,None,None,None,5000000.0,None,NaN,600000000,6215000000,908000000.0,14162000000,6397000000,"10-Q, 0001193125-10-233883",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1390000000.0,2099000000.0,243000000.0,131000000.0
29,Q2,2010,None,None,1629000000,3479000000,1940000000,805000000,8118000000,NaN,1229000000,1317000000,12397000000,None,3545000000,1705000000,5250000000,None,None,None,None,5000000.0,None,NaN,600000000,6056000000,678000000.0,12397000000,5857000000,"10-Q, 0001193125-10-164083",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1290000000.0,1704000000.0,294000000.0,282000000.0
30,Q1,2010,None,None,1844000000,3219000000,1820000000,815000000,7964000000,NaN,1234000000,1392000000,12042000000,None,3619000000,1574000000,5193000000,None,None,None,None,5000000.0,None,NaN,600000000,5887000000,471000000.0,12042000000,5618000000,"10-Q, 0001193125-10-090367",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1231000000.0,1436000000.0,282000000.0,145000000.0
31,Q3,2009,None,None,2514000000,1487000000,1617000000,671000000,6369000000,NaN,457000000,854000000,8972000000,None,3354000000,1183000000,4537000000,None,None,None,None,4000000.0,None,NaN,600000000,4428000000,212000000.0,8972000000,3585000000,"10-Q, 0001193125-09-212134",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,850000000.0,1086000000.0,286000000.0,35000000.0
32,Q2,2009,None,None,1936000000,1276000000,1325000000,584000000,5304000000,NaN,451000000,821000000,7675000000,None,2508000000,1128000000,3636000000,None,None,None,None,4000000.0,None,NaN,600000000,4321000000,411000000.0,7675000000,3256000000,"10-Q, 0001193125-09-154174",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,783000000.0,981000000.0,301000000.0,58000000.0

## Deleting columns with null values above a certain threshold.

In [25]:
def del_empty_col( df ):
    
    for columns in df:
        
        df.replace(0, np.nan, inplace=True)
        
        if df[columns].isna().astype(int).mean() > 0.5:
            df.drop([columns], inplace=True, axis=1)
            
    df.fillna(0)
        
    return df

In [26]:
del_empty_col(abt).fillna(0)

,Quarter,Year,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Goodwill,Other assets,Total assets,Accounts payable,Accrued expenses and other,Total current liabilities,Common Stock,Treasury stock,Additional paid in capital,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.,Total non current liabilities,Total Property and Equipment,Deferred Revenue,Accumulated comprehensive income
0,Q1,2020,27201000000,22091000000,18857000000,17836000000,85985000000,14739000000,16456000000,221238000000,40056000000,30791000000,79711000000,5000000.0,1837000000,35412000000,33755000000.0,221238000000,65272000000,"10-Q, 0001018724-20-000010",76255000000.0,77779000000.0,8864000000.0,2063000000.0
1,Q3,2019,23255000000,20146000000,18766000000,16887000000,79054000000,14734000000,14535000000,199099000000,35794000000,28961000000,72136000000,5000000.0,1837000000,31817000000,27952000000.0,199099000000,56508000000,"10-Q, 0001018724-19-000089",70455000000.0,67662000000.0,7381000000.0,1429000000.0
2,Q2,2019,22616000000,18847000000,18580000000,16747000000,76790000000,14727000000,13462000000,191351000000,36063000000,26140000000,69678000000,5000000.0,1837000000,30035000000,25818000000.0,191351000000,53061000000,"10-Q, 0001018724-19-000071",68612000000.0,64723000000.0,7475000000.0,960000000.0
3,Q1,2019,23115000000,13905000000,16432000000,15979000000,69431000000,14708000000,12783000000,178102000000,31809000000,24588000000,63695000000,5000000.0,1837000000,28059000000,23193000000.0,178102000000,48410000000,"10-Q, 0001018724-19-000043",65997000000.0,61048000000.0,7298000000.0,1010000000.0
4,Q3,2018,20425000000,9340000000,15862000000,14258000000,59885000000,14553000000,11238000000,143695000000,30904000000,18420000000,55324000000,5000000.0,1837000000,25375000000,16616000000.0,143695000000,39125000000,"10-Q, 0001018724-18-000159",49246000000.0,58019000000.0,6000000000.0,1034000000.0
5,Q2,2018,19823000000,7227000000,14824000000,12607000000,54481000000,13944000000,10907000000,134100000000,27657000000,17140000000,50801000000,5000000.0,1837000000,24028000000,13733000000.0,134100000000,34995000000,"10-Q, 0001018724-18-000108",48304000000.0,54768000000.0,6004000000.0,934000000.0
6,Q1,2018,16676000000,8287000000,13840000000,12026000000,50829000000,13388000000,9814000000,126362000000,25172000000,16691000000,48045000000,5000000.0,1837000000,22563000000,11199000000.0,126362000000,31463000000,"10-Q, 0001018724-18-000072",46854000000.0,52331000000.0,6182000000.0,467000000.0
7,Q3,2017,12767000000,11543000000,13711000000,10557000000,48578000000,13271000000,8083000000,115267000000,26075000000,15844000000,47072000000,5000000.0,1837000000,20212000000,6779000000.0,115267000000,24658000000,"10-Q, 0001018724-17-000135",43537000000.0,45335000000.0,5153000000.0,501000000.0
8,Q2,2017,13203000000,8248000000,11510000000,8046000000,41007000000,4254000000,5437000000,87781000000,21439000000,14016000000,40520000000,5000000.0,1837000000,19129000000,6524000000.0,87781000000,23214000000,"10-Q, 0001018724-17-000100",24047000000.0,37083000000.0,5065000000.0,607000000.0
9,Q1,2017,15440000000,6091000000,10600000000,7329000000,39460000000,3823000000,5054000000,80969000000,18891000000,13054000000,37399000000,5000000.0,1837000000,17976000000,6327000000.0,80969000000,21674000000,"10-Q, 0001018724-17-000051",21896000000.0,32632000000.0,5454000000.0,797000000.0
10,Q3,2016,13656000000,4691000000,10696000000,6566000000,35609000000,3815000000,4296000000,70897000000,18801000000,10497000000,33498000000,5000000.0,1837000000,15968000000,4167000000.0,70897000000,17782000000,"10-Q, 0001018724-16-000324",19617000000.0,27177000000.0,4200000000.0,521000000.0
11,Q2,2016,12521000000,4019000000,9588000000,6092000000,32220000000,3774000000,3892000000,65076000000,16123000000,9613000000,29587000000,5000000.0,1837000000,15026000000,3915000000.0,65076000000,16538000000,"10-Q, 0001018724-16-000286",18951000000.0,25190000000.0,3851000000.0,571000000.0
12,Q1,2016,12470000000,3389000000,9582000000,5072000000,30513000000,3785000000,3522000000,61128000000,14990000000,9431000000,28187000000,5000000.0,1837000000,14144000000,3058000000.0,61128000000,14756000000,"10-Q, 0001018724-16-000227",18185000000.0,23308000000.0,3766000000.0,614000000.0
13,Q3,2015,10709000000,3719000000,8981000000,5440000000,28849000000,3529000000,3216000000,56230000000,14437000000,9157000000,26657000000,5000000.0,1837000000,12874000000,2063000000.0,56230000000,12430000000,"10-Q, 0001018724-15-000126",17143000000.0,20636000000.0,3063000000.0,675000000.0
14,Q2,2015,10269000000,3732000000,7470000000,4920000000,26391000000,3523000000,3047000000,52440000000,12391000000,8959000000,23912000000,5000000.0,1837000000,12233000000,1984000000.0,52440000000,11768000000,"10-Q, 0001018724-15-000087",16760000000.0,19479000000.0,2562000000.0,617000000.0
15,Q1,2015,10237000000,3544000000,7369000000,4772000000,25922000000,3491000000,2926000000,50075000000,11917000000,8840000000,23177000000,5000000.0,1837000000,11565000000,1892000000.0,50075000000,10873000000,"10-Q, 0001018724-15-000038",16025000000.0,17736000000.0,2420000000.0,752000000.0
16,Q3,2014,5258000000,1625000000,7316000000,4373000000,18572000000,3332000000,2813000000,40419000000,11811000000,7217000000,20842000000,5000000.0,1837000000,10827000000,1735000000.0,40419000000,10336000000,"10-Q, 0001018724-14-000055",9241000000.0,15702000000.0,1814000000.0,394000000.0
17,Q2,2014,5057000000,2929000000,6644000000,4125000000,18755000000,2677000000,2377000000,37898000000,10457000000,6688000000,18751000000,5000000.0,1837000000,10405000000,2172000000.0,37898000000,10602000000,"10-Q, 0001018724-14-000025",8545000000.0,14089000000.0,1606000000.0,143000000.0
18,Q1,2014,5074000000,3592000000,6716000000,3945000000,19327000000,2653000000,2117000000,36364000000,10590000000,6251000000,18357000000,5000000.0,1837000000,10019000000,2298000000.0,36364000000,10328000000,"10-Q, 0001018724-14-000014",7679000000.0,12267000000.0,1516000000.0,157000000.0
19,Q3,2013,3872000000,3817000000,6068000000,3057000000,17334000000,2635000000,1773000000,31861000000,10037000000,6098000000,16135000000,5000000.0,1837000000,9175000000,1950000000.0,31861000000,9087000000,"10-Q, 0001445305-13-002495",6639000000.0,9991000000.0,648000000.0,206000000.0
20,Q2,2013,3704000000,3759000000,5420000000,2861000000,16285000000,2614000000,1807000000,29623000000,8990000000,5745000000,14735000000,5000000.0,1837000000,8893000000,1991000000.0,29623000000,8733000000,"10-Q, 0001193125-13-303204",6155000000.0,8789000000.0,669000000.0,319000000.0
21,Q1,2013,4481000000,3414000000,5395000000,2516000000,16313000000,2535000000,1732000000,28377000000,8916000000,5416000000,14332000000,5000000.0,1837000000,8585000000,1998000000.0,28377000000,8432000000,"10-Q, 0001193125-13-174667",5613000000.0,7674000000.0,630000000.0,319000000.0
22,Q3,2012,2980000000,2268000000,5065000000,2392000000,13118000000,2540000000,1476000000,22834000000,8369000000,4236000000,12605000000,5000000.0,1837000000,7863000000,1818000000.0,22834000000,7553000000,"10-Q, 0001193125-12-436012",2676000000.0,5662000000.0,451000000.0,296000000.0
23,Q2,2012,2335000000,2635000000,4380000000,2035000000,11793000000,2521000000,1585000000,21022000000,7072000000,3892000000,10964000000,5000000.0,1837000000,7573000000,2092000000.0,21022000000,7505000000,"10-Q, 0001193125-12-317409",2553000000.0,5097000000.0,434000000.0,328000000.0
24,Q1,2012,2288000000,3427000000,4255000000,1813000000,12154000000,1970000000,1535000000,20339000000,6886000000,3602000000,10488000000,5000000.0,1837000000,7192000000,2085000000.0,20339000000,7271000000,"10-Q, 0001193125-12-187203",2580000000.0,4653000000.0,398000000.0,174000000.0
25,Q3,2011,2823000000,3503000000,3770000000,1496000000,11904000000,1934000000,1190000000,19054000000,6552000000,2426000000,8978000000,5000000.0,600000000,6824000000,1778000000.0,19054000000,7766000000,"10-Q, 0001193125-11-280739",2310000000.0,3999000000.0,339000000.0,241000000.0
26,Q2,2011,2047000000,4308000000,3229000000,1438000000,11279000000,1909000000,1253000000,17941000000,5721000000,2324000000,8045000000,5000000.0,600000000,6675000000,1715000000.0,17941000000,7765000000,"10-Q, 0001193125-11-197823",2131000000.0,3470000000.0,287000000.0,30000000.0
27,Q1,2011,2641000000,4240000000,2888000000,1304000000,11288000000,1513000000,1151000000,16882000000,5540000000,2190000000,7730000000,5000000.0,600000000,6483000000,1525000000.0,16882000000,7347000000,"10-Q, 0001193125-11-110197",1805000000.0,2902000000.0,243000000.0,66000000.0
28,Q3,2010,1539000000,4346000000,2515000000,959000000,9559000000,1277000000,1184000000,14162000000,4614000000,1761000000,6375000000,5000000.0,600000000,6215000000,908000000.0,14162000000,6397000000,"10-Q, 0001193125-10-233883",1390000000.0,2099000000.0,243000000.0,131000000.0
29,Q2,2010,1629000000,3479000000,1940000000,805000000,8118000000,1229000000,1317000000,12397000000,3545000000,1705000000,5250000000,5000000.0,600000000,6056000000,678000000.0,12397000000,5857000000,"10-Q, 0001193125-10-164083",1290000000.0,1704000000.0,294000000.0,282000000.0
30,Q1,2010,1844000000,3219000000,1820000000,815000000,7964000000,1234000000,1392000000,12042000000,3619000000,1574000000,5193000000,5000000.0,600000000,5887000000,471000000.0,12042000000,5618000000,"10-Q, 0001193125-10-090367",1231000000.0,1436000000.0,282000000.0,145000000.0
31,Q3,2009,2514000000,1487000000,1617000000,671000000,6369000000,457000000,854000000,8972000000,3354000000,1183000000,4537000000,4000000.0,600000000,4428000000,212000000.0,8972000000,3585000000,"10-Q, 0001193125-09-212134",850000000.0,1086000000.0,286000000.0,35000000.0
32,Q2,2009,1936000000,1276000000,1325000000,584000000,5304000000,451000000,821000000,7675000000,2508000000,1128000000,3636000000,4000000.0,600000000,4321000000,411000000.0,7675000000,3256000000,"10-Q, 0001193125-09-154174",783000000.0,981000000.0,301000000.0,58000000.0
33,Q1,2009,1701000000,1029000000,1266000000,587000000,4775000000,433000000,765000000,6980000000,2380000000,1030000000,3410000000,4000000.0,600000000,4210000000,553000000.0,6980000000,2918000000,"10-Q, 0001193125-09-085983",652000000.0,889000000.0,310000000.0,143000000.0
34,Q3,2008,1650000000,674000000,1315000000,597000000,4430000000,405000000,722000000,6566000000,2242000000,860000000,3144000000,4000000.0,500000000,4051000000,955000000.0,6566000000,2527000000,"10-Q, 0001193125-08-214483",895000000.0,731000000.0,472000000.0,73000000.0
35,Q2,2008,1548000000,832000000,1107000000,586000000,4236000000,400000000,751000000,6322000000,1963000000,812000000,3216000000,4000000.0,500000000,3794000000,1074000000.0,6322000000,2230000000,"10-Q, 0001193125-08-157451",876000000.0,651000000.0,447000000.0,6000000.0
36,Q1,2008,1496000000,655000000,1077000000,581000000,3965000000,392000000,652000000,5883000000,1864000000,781000000,3551000000,4000000.0,500000000,3191000000,1232000000.0,5883000000,1470000000,"10-Q, 0001193125-08-089548",862000000.0,594000000.0,436000000.0,7000000.0
37,Q4,2019,36092000000,18929000000,20497000000,20816000000,96334000000,14754000000,16314000000,225248000000,47183000000,32439000000,87812000000,5000000.0,1837000000,33658000000,31220000000.0,225248000000,62060000000,"10-K, 0001018724-20-000004",75376000000.0,72705000000.0,8190000000.0,986000000.0
38,Q4,2018,31750000000,9500000000,17174000000,16677000000,75101000000,14548000000,11202000000,162648000000,38192000000,23663000000,68391000000,5000000.0,1837000000,26791000000,19625000000.0,162648000000,43549000000,"10-K, 0001018724-19-000004",50708000000.0,61797000000.0,6536000000.0,1035000000.0
39,Q4,2017,20522000000,10464000000,16047000000,13164000000,60197000000,13350000000,8897000000,131310000000,34616000000,18170000000,57883000000,5000000.0,1837000000,21389000000,8636000000.0,131310000000,27709000000,"10-K, 0001018724-18-000005",45718000000.0,48866000000.0,5097000000.0,484000000.0
40,Q4,2016,19334000000,6647000000,11461000000,8339000000,45781000000,3784000000,4723000000,83402000000,25309000000,13739000000,43816000000,5000000.0,1837000000,17186000000,4916000000.0,83402000000,19285000000,"10-K, 0001018724-17-000011",20301000000.0,29114000000.0,4768000000.0,985000000.0
41,Q4,2015,14557000000,2859000000,8299000000,5612000000,31327000000,3319000000,2892000000,54505000000,16459000000,9807000000,28089000000,5000000.0,1837000000,11135000000,1949000000.0,54505000000,10741000000,"10-K, 0001018724-16-000172",15675000000.0,16967000000.0,1823000000.0,511000000.0
42,Q4,2014,8658000000,3789000000,7411000000,4767000000,24625000000,2655000000,1930000000,40159000000,15133000000,6688000000,22980000000,5000000.0,1837000000,9573000000,2190000000.0,40159000000,9746000000,"10-K, 0001018724-15-000006",7433000000.0,10949000000.0,1159000000.0,185000000.0
43,Q4,2013,8084000000,3364000000,6031000000,3817000000,21296000000,2552000000,1647000000,32555000000,13318000000,4892000000,19002000000,5000000.0,1837000000,8347000000,1916000000.0,32555000000,8192000000,"10-K, 0001018724-14-000006",5361000000.0,7060000000.0,792000000.0,239000000.0
44,Q4,2012,5269000000,4307000000,4992000000,2571000000,17490000000,1955000000,1388000000,25278000000,11145000000,3751000000,14896000000,5000000.0,877000000,6990000000,1955000000.0,25278000000,7757000000,"10-K, 0001193125-13-028520",2625000000.0,4417000000.0,379000000.0,316000000.0
45,Q4,2011,3777000000,4985000000,3202000000,1587000000,13747000000,1349000000,1265000000,18797000000,8051000000,2321000000,10372000000,5000000.0,600000000,6325000000,1324000000.0,18797000000,6864000000,"10-K, 0001193125-12-032846",1561000000.0,2414000000.0,218000000.0,190000000.0
46,Q4,2010,3444000000,2922000000,2171000000,988000000,9797000000,1234000000,1474000000,13813000000,5605000000,1759000000,7364000000,5000000.0,600000000,5736000000,172000000.0,13813000000,5257000000,"10-K, 0001193125-11-016253",1192000000.0,1290000000.0,290000000.0,56000000.0
47,Q4,2009,2769000000,958000000,1399000000,827000000,6157000000,438000000,720000000,8314000000,3594000000,1152000000,4746000000,4000000.0,600000000,4121000000,730000000.0,8314000000,2672000000,"10-K, 0001193125-10-016098",896000000.0,854000000.0,349000000.0,123000000.0
48,Q4,2008,2539000000,573000000,1200000000,705000000,5164000000,222000000,296000000,6485000000,2795000000,902000000,3714000000,4000000.0,500000000,3063000000,1375000000.0,6485000000,1197000000,"10-K, 0001193125-09-014406",1574000000.0,543000000.0,407000000.0,5000000.0
49,Q4,2007,1022000000,997000000,877000000,399000000,3373000000,195000000,139000000,4363000000,1816000000,716000000,2532000000,4000000.0,252000000,2517000000,1837000000.0,4363000000,431000000,"10-K, 0001193125-08-024707",1400000000.0,457000000.0,277000000.0,1000000.0

In [27]:
# Just for checking.
def checking_duplicate_columns( DataF ):
    
    duplicates = [k for (k,v) in Counter(DataF.columns).items() if v > 1] 
    
    print('Shape of df: ', DataF.shape )
    return duplicates

In [28]:
checking_duplicate_columns(abt)

Shape of df:  (50, 24)

[]

In [29]:
abt

,Quarter,Year,Cash,Marketable securities,Inventory,Accounts Receivable,Total current assets,Goodwill,Other assets,Total assets,Accounts payable,Accrued expenses and other,Total current liabilities,Common Stock,Treasury stock,Additional paid in capital,Retained Earnings,Total liabilities and equity,Total Shareholder Equity,Filing/Acc.No.,Total non current liabilities,Total Property and Equipment,Deferred Revenue,Accumulated comprehensive income
0,Q1,2020,27201000000,22091000000,18857000000,17836000000,85985000000,14739000000,16456000000,221238000000,40056000000,30791000000,79711000000,5000000.0,1837000000,35412000000,33755000000.0,221238000000,65272000000,"10-Q, 0001018724-20-000010",76255000000.0,77779000000.0,8864000000.0,2063000000.0
1,Q3,2019,23255000000,20146000000,18766000000,16887000000,79054000000,14734000000,14535000000,199099000000,35794000000,28961000000,72136000000,5000000.0,1837000000,31817000000,27952000000.0,199099000000,56508000000,"10-Q, 0001018724-19-000089",70455000000.0,67662000000.0,7381000000.0,1429000000.0
2,Q2,2019,22616000000,18847000000,18580000000,16747000000,76790000000,14727000000,13462000000,191351000000,36063000000,26140000000,69678000000,5000000.0,1837000000,30035000000,25818000000.0,191351000000,53061000000,"10-Q, 0001018724-19-000071",68612000000.0,64723000000.0,7475000000.0,960000000.0
3,Q1,2019,23115000000,13905000000,16432000000,15979000000,69431000000,14708000000,12783000000,178102000000,31809000000,24588000000,63695000000,5000000.0,1837000000,28059000000,23193000000.0,178102000000,48410000000,"10-Q, 0001018724-19-000043",65997000000.0,61048000000.0,7298000000.0,1010000000.0
4,Q3,2018,20425000000,9340000000,15862000000,14258000000,59885000000,14553000000,11238000000,143695000000,30904000000,18420000000,55324000000,5000000.0,1837000000,25375000000,16616000000.0,143695000000,39125000000,"10-Q, 0001018724-18-000159",49246000000.0,58019000000.0,6000000000.0,1034000000.0
5,Q2,2018,19823000000,7227000000,14824000000,12607000000,54481000000,13944000000,10907000000,134100000000,27657000000,17140000000,50801000000,5000000.0,1837000000,24028000000,13733000000.0,134100000000,34995000000,"10-Q, 0001018724-18-000108",48304000000.0,54768000000.0,6004000000.0,934000000.0
6,Q1,2018,16676000000,8287000000,13840000000,12026000000,50829000000,13388000000,9814000000,126362000000,25172000000,16691000000,48045000000,5000000.0,1837000000,22563000000,11199000000.0,126362000000,31463000000,"10-Q, 0001018724-18-000072",46854000000.0,52331000000.0,6182000000.0,467000000.0
7,Q3,2017,12767000000,11543000000,13711000000,10557000000,48578000000,13271000000,8083000000,115267000000,26075000000,15844000000,47072000000,5000000.0,1837000000,20212000000,6779000000.0,115267000000,24658000000,"10-Q, 0001018724-17-000135",43537000000.0,45335000000.0,5153000000.0,501000000.0
8,Q2,2017,13203000000,8248000000,11510000000,8046000000,41007000000,4254000000,5437000000,87781000000,21439000000,14016000000,40520000000,5000000.0,1837000000,19129000000,6524000000.0,87781000000,23214000000,"10-Q, 0001018724-17-000100",24047000000.0,37083000000.0,5065000000.0,607000000.0
9,Q1,2017,15440000000,6091000000,10600000000,7329000000,39460000000,3823000000,5054000000,80969000000,18891000000,13054000000,37399000000,5000000.0,1837000000,17976000000,6327000000.0,80969000000,21674000000,"10-Q, 0001018724-17-000051",21896000000.0,32632000000.0,5454000000.0,797000000.0
10,Q3,2016,13656000000,4691000000,10696000000,6566000000,35609000000,3815000000,4296000000,70897000000,18801000000,10497000000,33498000000,5000000.0,1837000000,15968000000,4167000000.0,70897000000,17782000000,"10-Q, 0001018724-16-000324",19617000000.0,27177000000.0,4200000000.0,521000000.0
11,Q2,2016,12521000000,4019000000,9588000000,6092000000,32220000000,3774000000,3892000000,65076000000,16123000000,9613000000,29587000000,5000000.0,1837000000,15026000000,3915000000.0,65076000000,16538000000,"10-Q, 0001018724-16-000286",18951000000.0,25190000000.0,3851000000.0,571000000.0
12,Q1,2016,12470000000,3389000000,9582000000,5072000000,30513000000,3785000000,3522000000,61128000000,14990000000,9431000000,28187000000,5000000.0,1837000000,14144000000,3058000000.0,61128000000,14756000000,"10-Q, 0001018724-16-000227",18185000000.0,23308000000.0,3766000000.0,614000000.0
13,Q3,2015,10709000000,3719000000,8981000000,5440000000,28849000000,3529000000,3216000000,56230000000,14437000000,9157000000,26657000000,5000000.0,1837000000,12874000000,2063000000.0,56230000000,12430000000,"10-Q, 0001018724-15-000126",17143000000.0,20636000000.0,3063000000.0,675000000.0
14,Q2,2015,10269000000,3732000000,7470000000,4920000000,26391000000,3523000000,3047000000,52440000000,12391000000,8959000000,23912000000,5000000.0,1837000000,12233000000,1984000000.0,52440000000,11768000000,"10-Q, 0001018724-15-000087",16760000000.0,19479000000.0,2562000000.0,617000000.0
15,Q1,2015,10237000000,3544000000,7369000000,4772000000,25922000000,3491000000,2926000000,50075000000,11917000000,8840000000,23177000000,5000000.0,1837000000,11565000000,1892000000.0,50075000000,10873000000,"10-Q, 0001018724-15-000038",16025000000.0,17736000000.0,2420000000.0,752000000.0
16,Q3,2014,5258000000,1625000000,7316000000,4373000000,18572000000,3332000000,2813000000,40419000000,11811000000,7217000000,20842000000,5000000.0,1837000000,10827000000,1735000000.0,40419000000,10336000000,"10-Q, 0001018724-14-000055",9241000000.0,15702000000.0,1814000000.0,394000000.0
17,Q2,2014,5057000000,2929000000,6644000000,4125000000,18755000000,2677000000,2377000000,37898000000,10457000000,6688000000,18751000000,5000000.0,1837000000,10405000000,2172000000.0,37898000000,10602000000,"10-Q, 0001018724-14-000025",8545000000.0,14089000000.0,1606000000.0,143000000.0
18,Q1,2014,5074000000,3592000000,6716000000,3945000000,19327000000,2653000000,2117000000,36364000000,10590000000,6251000000,18357000000,5000000.0,1837000000,10019000000,2298000000.0,36364000000,10328000000,"10-Q, 0001018724-14-000014",7679000000.0,12267000000.0,1516000000.0,157000000.0
19,Q3,2013,3872000000,3817000000,6068000000,3057000000,17334000000,2635000000,1773000000,31861000000,10037000000,6098000000,16135000000,5000000.0,1837000000,9175000000,1950000000.0,31861000000,9087000000,"10-Q, 0001445305-13-002495",6639000000.0,9991000000.0,648000000.0,206000000.0
20,Q2,2013,3704000000,3759000000,5420000000,2861000000,16285000000,2614000000,1807000000,29623000000,8990000000,5745000000,14735000000,5000000.0,1837000000,8893000000,1991000000.0,29623000000,8733000000,"10-Q, 0001193125-13-303204",6155000000.0,8789000000.0,669000000.0,319000000.0
21,Q1,2013,4481000000,3414000000,5395000000,2516000000,16313000000,2535000000,1732000000,28377000000,8916000000,5416000000,14332000000,5000000.0,1837000000,8585000000,1998000000.0,28377000000,8432000000,"10-Q, 0001193125-13-174667",5613000000.0,7674000000.0,630000000.0,319000000.0
22,Q3,2012,2980000000,2268000000,5065000000,2392000000,13118000000,2540000000,1476000000,22834000000,8369000000,4236000000,12605000000,5000000.0,1837000000,7863000000,1818000000.0,22834000000,7553000000,"10-Q, 0001193125-12-436012",2676000000.0,5662000000.0,451000000.0,296000000.0
23,Q2,2012,2335000000,2635000000,4380000000,2035000000,11793000000,2521000000,1585000000,21022000000,7072000000,3892000000,10964000000,5000000.0,1837000000,7573000000,2092000000.0,21022000000,7505000000,"10-Q, 0001193125-12-317409",2553000000.0,5097000000.0,434000000.0,328000000.0
24,Q1,2012,2288000000,3427000000,4255000000,1813000000,12154000000,1970000000,1535000000,20339000000,6886000000,3602000000,10488000000,5000000.0,1837000000,7192000000,2085000000.0,20339000000,7271000000,"10-Q, 0001193125-12-187203",2580000000.0,4653000000.0,398000000.0,174000000.0
25,Q3,2011,2823000000,3503000000,3770000000,1496000000,11904000000,1934000000,1190000000,19054000000,6552000000,2426000000,8978000000,5000000.0,600000000,6824000000,1778000000.0,19054000000,7766000000,"10-Q, 0001193125-11-280739",2310000000.0,3999000000.0,339000000.0,241000000.0
26,Q2,2011,2047000000,4308000000,3229000000,1438000000,11279000000,1909000000,1253000000,17941000000,5721000000,2324000000,8045000000,5000000.0,600000000,6675000000,1715000000.0,17941000000,7765000000,"10-Q, 0001193125-11-197823",2131000000.0,3470000000.0,287000000.0,30000000.0
27,Q1,2011,2641000000,4240000000,2888000000,1304000000,11288000000,1513000000,1151000000,16882000000,5540000000,2190000000,7730000000,5000000.0,600000000,6483000000,1525000000.0,16882000000,7347000000,"10-Q, 0001193125-11-110197",1805000000.0,2902000000.0,243000000.0,66000000.0
28,Q3,2010,1539000000,4346000000,2515000000,959000000,9559000000,1277000000,1184000000,14162000000,4614000000,1761000000,6375000000,5000000.0,600000000,6215000000,908000000.0,14162000000,6397000000,"10-Q, 0001193125-10-233883",1390000000.0,2099000000.0,243000000.0,131000000.0
29,Q2,2010,1629000000,3479000000,1940000000,805000000,8118000000,1229000000,1317000000,12397000000,3545000000,1705000000,5250000000,5000000.0,600000000,6056000000,678000000.0,12397000000,5857000000,"10-Q, 0001193125-10-164083",1290000000.0,1704000000.0,294000000.0,282000000.0
30,Q1,2010,1844000000,3219000000,1820000000,815000000,7964000000,1234000000,1392000000,12042000000,3619000000,1574000000,5193000000,5000000.0,600000000,5887000000,471000000.0,12042000000,5618000000,"10-Q, 0001193125-10-090367",1231000000.0,1436000000.0,282000000.0,145000000.0
31,Q3,2009,2514000000,1487000000,1617000000,671000000,6369000000,457000000,854000000,8972000000,3354000000,1183000000,4537000000,4000000.0,600000000,4428000000,212000000.0,8972000000,3585000000,"10-Q, 0001193125-09-212134",850000000.0,1086000000.0,286000000.0,35000000.0
32,Q2,2009,1936000000,1276000000,1325000000,584000000,5304000000,451000000,821000000,7675000000,2508000000,1128000000,3636000000,4000000.0,600000000,4321000000,411000000.0,7675000000,3256000000,"10-Q, 0001193125-09-154174",783000000.0,981000000.0,301000000.0,58000000.0
33,Q1,2009,1701000000,1029000000,1266000000,587000000,4775000000,433000000,765000000,6980000000,2380000000,1030000000,3410000000,4000000.0,600000000,4210000000,553000000.0,6980000000,2918000000,"10-Q, 0001193125-09-085983",652000000.0,889000000.0,310000000.0,143000000.0
34,Q3,2008,1650000000,674000000,1315000000,597000000,4430000000,405000000,722000000,6566000000,2242000000,860000000,3144000000,4000000.0,500000000,4051000000,955000000.0,6566000000,2527000000,"10-Q, 0001193125-08-214483",895000000.0,731000000.0,472000000.0,73000000.0
35,Q2,2008,1548000000,832000000,1107000000,586000000,4236000000,400000000,751000000,6322000000,1963000000,812000000,3216000000,4000000.0,500000000,3794000000,1074000000.0,6322000000,2230000000,"10-Q, 0001193125-08-157451",876000000.0,651000000.0,447000000.0,6000000.0
36,Q1,2008,1496000000,655000000,1077000000,581000000,3965000000,392000000,652000000,5883000000,1864000000,781000000,3551000000,4000000.0,500000000,3191000000,1232000000.0,5883000000,1470000000,"10-Q, 0001193125-08-089548",862000000.0,594000000.0,436000000.0,7000000.0
37,Q4,2019,36092000000,18929000000,20497000000,20816000000,96334000000,14754000000,16314000000,225248000000,47183000000,32439000000,87812000000,5000000.0,1837000000,33658000000,31220000000.0,225248000000,62060000000,"10-K, 0001018724-20-000004",75376000000.0,72705000000.0,8190000000.0,986000000.0
38,Q4,2018,31750000000,9500000000,17174000000,16677000000,75101000000,14548000000,11202000000,162648000000,38192000000,23663000000,68391000000,5000000.0,1837000000,26791000000,19625000000.0,162648000000,43549000000,"10-K, 0001018724-19-000004",50708000000.0,61797000000.0,6536000000.0,1035000000.0
39,Q4,2017,20522000000,10464000000,16047000000,13164000000,60197000000,13350000000,8897000000,131310000000,34616000000,18170000000,57883000000,5000000.0,1837000000,21389000000,8636000000.0,131310000000,27709000000,"10-K, 0001018724-18-000005",45718000000.0,48866000000.0,5097000000.0,484000000.0
40,Q4,2016,19334000000,6647000000,11461000000,8339000000,45781000000,3784000000,4723000000,83402000000,25309000000,13739000000,43816000000,5000000.0,1837000000,17186000000,4916000000.0,83402000000,19285000000,"10-K, 0001018724-17-000011",20301000000.0,29114000000.0,4768000000.0,985000000.0
41,Q4,2015,14557000000,2859000000,8299000000,5612000000,31327000000,3319000000,2892000000,54505000000,16459000000,9807000000,28089000000,5000000.0,1837000000,11135000000,1949000000.0,54505000000,10741000000,"10-K, 0001018724-16-000172",15675000000.0,16967000000.0,1823000000.0,511000000.0
42,Q4,2014,8658000000,3789000000,7411000000,4767000000,24625000000,2655000000,1930000000,40159000000,15133000000,6688000000,22980000000,5000000.0,1837000000,9573000000,2190000000.0,40159000000,9746000000,"10-K, 0001018724-15-000006",7433000000.0,10949000000.0,1159000000.0,185000000.0
43,Q4,2013,8084000000,3364000000,6031000000,3817000000,21296000000,2552000000,1647000000,32555000000,13318000000,4892000000,19002000000,5000000.0,1837000000,8347000000,1916000000.0,32555000000,8192000000,"10-K, 0001018724-14-000006",5361000000.0,7060000000.0,792000000.0,239000000.0
44,Q4,2012,5269000000,4307000000,4992000000,2571000000,17490000000,1955000000,1388000000,25278000000,11145000000,3751000000,14896000000,5000000.0,877000000,6990000000,1955000000.0,25278000000,7757000000,"10-K, 0001193125-13-028520",2625000000.0,4417000000.0,379000000.0,316000000.0
45,Q4,2011,3777000000,4985000000,3202000000,1587000000,13747000000,1349000000,1265000000,18797000000,8051000000,2321000000,10372000000,5000000.0,600000000,6325000000,1324000000.0,18797000000,6864000000,"10-K, 0001193125-12-032846",1561000000.0,2414000000.0,218000000.0,190000000.0
46,Q4,2010,3444000000,2922000000,2171000000,988000000,9797000000,1234000000,1474000000,13813000000,5605000000,1759000000,7364000000,5000000.0,600000000,5736000000,172000000.0,13813000000,5257000000,"10-K, 0001193125-11-016253",1192000000.0,1290000000.0,290000000.0,56000000.0
47,Q4,2009,2769000000,958000000,1399000000,827000000,6157000000,438000000,720000000,8314000000,3594000000,1152000000,4746000000,4000000.0,600000000,4121000000,730000000.0,8314000000,2672000000,"10-K, 0001193125-10-016098",896000000.0,854000000.0,349000000.0,123000000.0
48,Q4,2008,2539000000,573000000,1200000000,705000000,5164000000,222000000,296000000,6485000000,2795000000,902000000,3714000000,4000000.0,500000000,3063000000,1375000000.0,6485000000,1197000000,"10-K, 0001193125-09-014406",1574000000.0,543000000.0,407000000.0,5000000.0
49,Q4,2007,1022000000,997000000,877000000,399000000,3373000000,195000000,139000000,4363000000,1816000000,716000000,2532000000,4000000.0,252000000,2517000000,1837000000.0,4363000000,431000000,"10-K, 0001193125-08-024707",1400000000.0,457000000.0,277000000.0,1000000.0

In [30]:
abt.to_csv('abt-Amazon.csv', index=False)

https://stackoverflow.com/questions/50950614/converting-column-into-multi-index-column

In [ ]:
imported_amzn = pd.read_csv('abt-Amazon.csv')
imported_amzn

In [ ]:
imported_amzn.isna().sum()

In [ ]:
new_col = list(abt.columns)
len(new_col) == len(set(new_col))

In [ ]:
set(original_col) - set(new_col)

In [ ]:
'Accumulated other comprehensive income '.strip()