# Problems

## - 'In Millions / Thousands' need multiplier info conveyed to cleaning_column()

## - Dictionary holding col_name varint

## - 'Property|equipment.'

# Capstone Project
## Structure : 
### 1) Import Libraries 
### 2) 2017 to 2020 
### 3) 2012 to 2016

# Libraries

In [4]:
# Import Library 

import re
import requests
import unicodedata
from bs4 import BeautifulSoup
from pprint import pprint
import numpy as np
from numpy import array
import pandas as pd 
import csv
import pickle
from IPython.display import display
import pickle
from collections import Counter
from IPython.core import display as ICD

pd.set_option('display.max_columns', 100)

In [5]:
master_filings_dict = {}
        
Accession_Number_URL = {}

AN_Active = {}

name_CIK = { 
    'Microsoft' :  ['0000789019']
}

dir_url = r'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK={}&type=10-&dateb=&owner=include&count=100'

doc_url = r'https://www.sec.gov/Archives/edgar/data/{CIKx}/{xx}/{yy}.txt'

In [6]:
# Dict of Companies -> CIK
for name, CIK_list in name_CIK.items():
    
    for CIK_position, CIK in enumerate(CIK_list):
        
        # CIK -> A_N 
        new_dir_url = dir_url.format( CIK )

        new_doc_url = doc_url.format(CIKx = CIK, xx='{xx}', yy='{yy}' )

        response = requests.get( new_dir_url )
        soup = BeautifulSoup( response.content, 'lxml' )
        text = soup.get_text( strip=True )

        cleaned_text = re.findall( 'Acc-no: \d+-\d+-\d+' , text )

        accession_number = [ n.replace('Acc-no: ', '') for n in cleaned_text ]
        accessionnumber = [ num.replace('-', '') for num in accession_number ]
        
        accession_numbers = zip(accessionnumber, accession_number)

        for a,b in accession_numbers: 
            
            file_url_list = new_doc_url.format(xx = a, yy = b)

            Accession_Number_URL.update({ b : file_url_list})
            
print('Accession_Number_URL - ', '\n', Accession_Number_URL)

Accession_Number_URL -
 {'0001564590-20-019706': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459020019706/0001564590-20-019706.txt', '0001564590-20-002450': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459020002450/0001564590-20-002450.txt', '0001564590-19-037549': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459019037549/0001564590-19-037549.txt', '0001564590-19-027952': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459019027952/0001564590-19-027952.txt', '0001564590-19-012709': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459019012709/0001564590-19-012709.txt', '0001564590-19-001392': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459019001392/0001564590-19-001392.txt', '0001564590-18-024893': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459018024893/0001564590-18-024893.txt', '0001564590-18-019062': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459018019062/0001564590-18-019062.txt', '0001564590-18-009307': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459018009307/0001564590-18-009307.txt', '0001564590-18-001129': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459018001129/0001564590-18-001129.txt', '0001564590-17-020171': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459017020171/0001564590-17-020171.txt', '0001564590-17-014900': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459017014900/0001564590-17-014900.txt', '0001564590-17-007547': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459017007547/0001564590-17-007547.txt', '0001564590-17-000654': 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459017000654/0001564590-17-000654.txt', '0001193125-16-742796': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312516742796/0001193125-16-742796.txt', '0001193125-16-662209': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312516662209/0001193125-16-662209.txt', '0001193125-16-550254': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312516550254/0001193125-16-550254.txt', '0001193125-16-441821': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312516441821/0001193125-16-441821.txt', '0001193125-15-350718': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312515350718/0001193125-15-350718.txt', '0001193125-15-272806': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312515272806/0001193125-15-272806.txt', '0001193125-15-144151': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312515144151/0001193125-15-144151.txt', '0001193125-15-020351': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312515020351/0001193125-15-020351.txt', '0001193125-14-380252': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312514380252/0001193125-14-380252.txt', '0001193125-14-289961': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312514289961/0001193125-14-289961.txt', '0001193125-14-157088': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312514157088/0001193125-14-157088.txt', '0001193125-14-018634': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312514018634/0001193125-14-018634.txt', '0001193125-13-409855': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312513409855/0001193125-13-409855.txt', '0001193125-13-310206': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312513310206/0001193125-13-310206.txt', '0001193125-13-160748': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312513160748/0001193125-13-160748.txt', '0001193125-13-022207': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312513022207/0001193125-13-022207.txt', '0001193125-12-427209': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312512427209/0001193125-12-427209.txt', '0001193125-12-316848': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312512316848/0001193125-12-316848.txt', '0001193125-12-170665': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312512170665/0001193125-12-170665.txt', '0001193125-12-026864': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312512026864/0001193125-12-026864.txt', '0001193125-12-017029': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312512017029/0001193125-12-017029.txt', '0001193125-11-276022': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312511276022/0001193125-11-276022.txt', '0001193125-11-200680': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312511200680/0001193125-11-200680.txt', '0001193125-11-115186': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312511115186/0001193125-11-115186.txt', '0001193125-11-015947': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312511015947/0001193125-11-015947.txt', '0001193125-10-239825': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312510239825/0001193125-10-239825.txt', '0001193125-10-171791': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312510171791/0001193125-10-171791.txt', '0001193125-10-090116': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312510090116/0001193125-10-090116.txt', '0001193125-10-015598': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312510015598/0001193125-10-015598.txt', '0001193125-09-212454': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312509212454/0001193125-09-212454.txt', '0001193125-09-158735': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312509158735/0001193125-09-158735.txt', '0001193125-09-085779': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312509085779/0001193125-09-085779.txt', '0001193125-09-009386': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312509009386/0001193125-09-009386.txt', '0001193125-08-215207': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312508215207/0001193125-08-215207.txt', '0001193125-08-162768': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312508162768/0001193125-08-162768.txt', '0001193125-08-089362': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312508089362/0001193125-08-089362.txt', '0001193125-08-011476': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312508011476/0001193125-08-011476.txt', '0001193125-07-225854': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312507225854/0001193125-07-225854.txt', '0001193125-07-170817': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312507170817/0001193125-07-170817.txt', '0001193125-07-091808': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312507091808/0001193125-07-091808.txt', '0001193125-07-013034': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312507013034/0001193125-07-013034.txt', '0001193125-06-215912': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312506215912/0001193125-06-215912.txt', '0001193125-06-180008': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312506180008/0001193125-06-180008.txt', '0001193125-06-091033': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312506091033/0001193125-06-091033.txt', '0001193125-06-045107': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312506045107/0001193125-06-045107.txt', '0001193125-06-012779': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312506012779/0001193125-06-012779.txt', '0001193125-05-209978': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312505209978/0001193125-05-209978.txt', '0001193125-05-174825': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312505174825/0001193125-05-174825.txt', '0001193125-05-088562': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312505088562/0001193125-05-088562.txt', '0001193125-05-013133': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312505013133/0001193125-05-013133.txt', '0001193125-04-189841': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312504189841/0001193125-04-189841.txt', '0001193125-04-150689': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312504150689/0001193125-04-150689.txt', '0001193125-04-076795': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312504076795/0001193125-04-076795.txt', '0001193125-04-016249': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312504016249/0001193125-04-016249.txt', '0001193125-03-080353': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312503080353/0001193125-03-080353.txt', '0001193125-03-045632': 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312503045632/0001193125-03-045632.txt', '0001032210-03-000809': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221003000809/0001032210-03-000809.txt', '0001032210-03-000121': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221003000121/0001032210-03-000121.txt', '0001032210-02-001614': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221002001614/0001032210-02-001614.txt', '0001032210-02-001351': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221002001351/0001032210-02-001351.txt', '0001032210-02-000709': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221002000709/0001032210-02-000709.txt', '0001032210-02-000453': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221002000453/0001032210-02-000453.txt', '0001032210-02-000454': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221002000454/0001032210-02-000454.txt', '0001032210-02-000132': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221002000132/0001032210-02-000132.txt', '0001032210-01-501233': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221001501233/0001032210-01-501233.txt', '0001032210-01-501099': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221001501099/0001032210-01-501099.txt', '0001032210-01-500604': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221001500604/0001032210-01-500604.txt', '0001032210-01-000273': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221001000273/0001032210-01-000273.txt', '0001032210-00-500038': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221000500038/0001032210-00-500038.txt', '0001032210-00-001961': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221000001961/0001032210-00-001961.txt', '0001032210-00-001019': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221000001019/0001032210-00-001019.txt', '0001032210-00-000218': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221000000218/0001032210-00-000218.txt', '0001032210-99-001526': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221099001526/0001032210-99-001526.txt', '0001032210-99-001375': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221099001375/0001032210-99-001375.txt', '0001032210-99-000791': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221099000791/0001032210-99-000791.txt', '0001032210-99-000191': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221099000191/0001032210-99-000191.txt', '0001032210-98-001218': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221098001218/0001032210-98-001218.txt', '0001032210-98-001067': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221098001067/0001032210-98-001067.txt', '0001032210-98-000581': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221098000581/0001032210-98-000581.txt', '0001032210-98-000519': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221098000519/0001032210-98-000519.txt', '0001032210-98-000171': 'https://www.sec.gov/Archives/edgar/data/0000789019/000103221098000171/0001032210-98-000171.txt', '0000898430-97-004575': 'https://www.sec.gov/Archives/edgar/data/0000789019/000089843097004575/0000898430-97-004575.txt', '0001017062-97-001764': 'https://www.sec.gov/Archives/edgar/data/0000789019/000101706297001764/0001017062-97-001764.txt', '0000891020-97-000879': 'https://www.sec.gov/Archives/edgar/data/0000789019/000089102097000879/0000891020-97-000879.txt', '0000891020-97-000207': 'https://www.sec.gov/Archives/edgar/data/0000789019/000089102097000207/0000891020-97-000207.txt', '0000891020-96-001463': 'https://www.sec.gov/Archives/edgar/data/0000789019/000089102096001463/0000891020-96-001463.txt'}

## Cleaning Columns Function

In [7]:
month_dict = {'December' : 'Q4',
              'November' : 'Q4',
             'October' : 'Q4',
             'September' : 'Q3',
             'August': 'Q3',
             'July' : 'Q3',
             'June' : 'Q2',
             'May' : 'Q2',
             'April' : 'Q2',
             'March' : 'Q1',
             'Feburary' : 'Q1',
             'January' : 'Q1'}

In [8]:
col_name_variants = {
    'Inventor' : 'Inventory',
    'Total liabilities and' : 'Total liabilities and equity',
    'Common stock.*' : 'Common Stock',
    'Preferred stock.*': 'Preferred Stock',
    'Accounts receivable.*' : 'Accounts Receivable',
    'Accrued liabilities.*' : 'Accrued Liabilities',
    'Deferred revenue.*' : 'Deferred Revenue',
    'Redeemable noncontrolling interests in subsidiaries.*' : 'Noncontrolling interests in subsidiaries',
    'Short term investments.*' : 'Short term investments', 
    'Property|equipment.' : 'Property and Equipment',
    'Retained earnings.*' : 'Retained Earnings',
    'stockholders.*' : 'Shareholder Equity',
    '^Cash.*' : 'Cash',
    'Convertible senior notes.*' : 'Convertible Senior Notes'
}

In [9]:
def clean_col_name( name ):
    
    for detect, replacement in col_name_variants.items():

        if re.findall(detect, name, flags=re.I):

            n_column = name.replace(name, replacement) 

            return n_column 
            
    return name

## Cleaning Tables Function

In [10]:
# Throw column list-like object into cleaning function. 
def cleaning_column(r_column):
     
    column_list = []
    column_name = []
    
    for element_post, element in enumerate(r_column):
        
        # Handling the first "row" in the table i.e. column name.
        if element_post == 0:

            ele_norm = unicodedata.normalize('NFKD', element)
            
            ele_norm = ele_norm.replace('net', '')
            
            ele_norm = ele_norm.replace( '-', ' ')
            
            s_ele_norm = re.sub(r"^\s+|\s+$", "", ele_norm)
            
            name = re.sub(r'(?=,|:|\.|\(){1}.*', repl='', string= s_ele_norm, flags=re.I)
            
            # clean_col_name function Choose old_if or new_dict
            clean_name = clean_col_name( name )
            ###
            column_name.append(clean_name)
            ###
            column_list.append(clean_name)
        
        # Handling the all the remaining "rows" in the table i.e. data/numbers.
        elif element not in ['\n$', '\n\xa0', '\n']:
                        
            n_element = element.replace( ',', '' )

            pattern = re.compile(r'[\d]+,[\d]+|[\d]+')

            res = pattern.findall(n_element)

            res = [int(ele) * 10**6 for ele in res]

            column_list.extend(res)

    return column_list

In [11]:
# New and imporved.
def Quarter( column ):
    
    print('column used for quarter', column)
    multi_list = [p_s_ele_norm.split() for p_s_ele_norm in column if p_s_ele_norm.split() != []]
#     print('multi_list', multi_list)
    new_column = [item for sublist in multi_list for item in sublist]
    print('new_column used for year', new_column)
    Q = []
    Y = []
    
    for letter in column:
#         print('letter', letter)
        try:
            month = re.findall(r'\w{}+'.format(list(month_dict.keys())), letter.replace(' ',  '') )[0]
            
            Q_num = month_dict[month] 
    #         print('Q_num' , Q_num)
    
            if Q_num != []:
                Q.append(Q_num)
                
        except:
            continue
    #         print('~'*20)
        
    print('Q' , Q) 
#     Q_final = Q[0] 
#     print('Q_final' , Q_final)
    
    Q_final =['Quarter'] + Q[:1]
    
    for letter in new_column:   
        
        #print( letter.split(',') )
        
        Year = [re.compile(r'^[0-9]{4}$').findall(p_s_ele_norm) for p_s_ele_norm in letter.split(',') if re.compile(r'^[0-9]{4}$').findall(p_s_ele_norm) != []]
        Y.append(Year)
    Y = [item for sublist in Y for item in sublist][0]
    
    Y.insert(0, 'Year')
    #Y.insert(1, 0)
    #Y.insert(1, 0)
    return Q_final, Y
    print( '\n', 'Q_final', Q_final, 'Y', Y)

In [12]:
A_N = []
for AN, url in Accession_Number_URL.items():
    
    if AN == '0001193125-12-170665':
        break
        
    else:
        A_N.append(AN)
        print(url)
        
print(A_N, '\n')
print(len(A_N))

https://www.sec.gov/Archives/edgar/data/0000789019/000156459020019706/0001564590-20-019706.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459020002450/0001564590-20-002450.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459019037549/0001564590-19-037549.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459019027952/0001564590-19-027952.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459019012709/0001564590-19-012709.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459019001392/0001564590-19-001392.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459018024893/0001564590-18-024893.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459018019062/0001564590-18-019062.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459018009307/0001564590-18-009307.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459018001129/0001564590-18-001129.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459017020171/0001564590-17-020171.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459017014900/0001564590-17-014900.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459017007547/0001564590-17-007547.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000156459017000654/0001564590-17-000654.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312516742796/0001193125-16-742796.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312516662209/0001193125-16-662209.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312516550254/0001193125-16-550254.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312516441821/0001193125-16-441821.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312515350718/0001193125-15-350718.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312515272806/0001193125-15-272806.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312515144151/0001193125-15-144151.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312515020351/0001193125-15-020351.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312514380252/0001193125-14-380252.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312514289961/0001193125-14-289961.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312514157088/0001193125-14-157088.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312514018634/0001193125-14-018634.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312513409855/0001193125-13-409855.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312513310206/0001193125-13-310206.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312513160748/0001193125-13-160748.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312513022207/0001193125-13-022207.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312512427209/0001193125-12-427209.txt
https://www.sec.gov/Archives/edgar/data/0000789019/000119312512316848/0001193125-12-316848.txt
['0001564590-20-019706', '0001564590-20-002450', '0001564590-19-037549', '0001564590-19-027952', '0001564590-19-012709', '0001564590-19-001392', '0001564590-18-024893', '0001564590-18-019062', '0001564590-18-009307', '0001564590-18-001129', '0001564590-17-020171', '0001564590-17-014900', '0001564590-17-007547', '0001564590-17-000654', '0001193125-16-742796', '0001193125-16-662209', '0001193125-16-550254', '0001193125-16-441821', '0001193125-15-350718', '0001193125-15-272806', '0001193125-15-144151', '0001193125-15-020351', '0001193125-14-380252', '0001193125-14-289961', '0001193125-14-157088', '0001193125-14-018634', '0001193125-13-409855', '0001193125-13-310206', '0001193125-13-160748', '0001193125-13-022207', '0001193125-12-427209', '0001193125-12-316848']

32

## 2017 - 2020

### Creating the .htm urls to get key. post 2016 keys are #BALANCE_SHEETS

In [13]:
AN_Active = {}
# Get filename, method 3, use htm.# anchor to jump to Balnce sheet.
for AN, url in Accession_Number_URL.items():
    
    # Break is needed to limit lower bound, either 
    # pre-2016 = 0001193125-12-170665 (if excludes -12-170665 ) or 
    # post-16 = 0001193125-16-742796 (x > 16, excludes 16)
    
    # if statement takes in Acc-Num format: xx-xxx-xx
    if AN == '0001193125-12-170665':
        break
        
    if int( AN.split( sep='-' )[1] ) > 12:
        print('~'*75)
        r = requests.get(url)
        
        try: 
            soup = BeautifulSoup(r.content, "html")
            
        except:
            print('Look at: ')
            print( '{} - {}'.format(AN, url))
            
        # 1.0
        AccessionNumber = AN.replace('-', '')
        
        # 2.1 part of table website.
        filename = str(soup.find('filename').contents[0]).replace('\n', '')
        print('filename - ', filename, '\n')
        
        # 2.2 Anchor page_key.
        hr_tag = soup.findAll('a', href=True)
        page_key = str( [table.get('href') for table in hr_tag if 'Balance Sheets' in table.get_text()][0])
        print('page_key - ', page_key, '\n')
        
        KEY = filename + page_key
        
        active_url = new_doc_url.format( xx = AccessionNumber, yy = KEY ).replace('.txt', '')

        print('active_url - ', active_url)
        
        # Key for 2016 onwards is the same, will overwrite the keys() in AN_Active. 
        AN_Active.update({ AN : [ page_key , active_url ] } )

    else:
        continue

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Look at:
0001564590-20-019706 - https://www.sec.gov/Archives/edgar/data/0000789019/000156459020019706/0001564590-20-019706.txt

AttributeError: 'NoneType' object has no attribute 'contents'

In [21]:
AN_Active

{'0001564590-20-019706': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459020019706/msft-10q_20200331.htm#BALANCE_SHEETS'],
 '0001564590-20-002450': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459020002450/msft-10q_20191231.htm#BALANCE_SHEETS'],
 '0001564590-19-037549': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459019037549/msft-10q_20190930.htm#BALANCE_SHEETS'],
 '0001564590-19-027952': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459019027952/msft-10k_20190630.htm#BALANCE_SHEETS'],
 '0001564590-19-012709': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459019012709/msft-10q_20190331.htm#BALANCE_SHEETS'],
 '0001564590-19-001392': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459019001392/msft-10q_20181231.htm#BALANCE_SHEETS'],
 '0001564590-18-024893': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459018024893/msft-10q_20180930.htm#BALANCE_SHEETS'],
 '0001564590-18-019062': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459018019062/msft-10k_20180630.htm#BALANCE_SHEETS'],
 '0001564590-18-009307': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459018009307/msft-10q_20180331.htm#BALANCE_SHEETS'],
 '0001564590-18-001129': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459018001129/msft-10q_20171231.htm#BALANCE_SHEETS'],
 '0001564590-17-020171': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459017020171/msft-10q_20170930.htm#BALANCE_SHEETS'],
 '0001564590-17-014900': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459017014900/msft-10k_20170630.htm#BALANCE_SHEETS'],
 '0001564590-17-007547': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459017007547/msft-10q_20170331.htm#BALANCE_SHEETS'],
 '0001564590-17-000654': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459017000654/msft-10q_20161231.htm#BALANCE_SHEETS'],
 '0001193125-16-742796': ['#tx245252_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312516742796/d245252d10q.htm#tx245252_5'],
 '0001193125-16-662209': ['#tx187868_27',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312516662209/d187868d10k.htm#tx187868_27'],
 '0001193125-16-550254': ['#tx256147_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312516550254/d256147d10q.htm#tx256147_5'],
 '0001193125-16-441821': ['#tx15167_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312516441821/d15167d10q.htm#tx15167_5'],
 '0001193125-15-350718': ['#tx83804_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312515350718/d83804d10q.htm#tx83804_5'],
 '0001193125-15-272806': ['#tx918813_32',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312515272806/d918813d10k.htm#tx918813_32'],
 '0001193125-15-144151': ['#tx860721_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312515144151/d860721d10q.htm#tx860721_5'],
 '0001193125-15-020351': ['#tx827041_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312515020351/d827041d10q.htm#tx827041_5'],
 '0001193125-14-380252': ['#tx770268_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312514380252/d770268d10q.htm#tx770268_5'],
 '0001193125-14-289961': ['#tx722626_27',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312514289961/d722626d10k.htm#tx722626_27'],
 '0001193125-14-157088': ['#tx695543_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312514157088/d695543d10q.htm#tx695543_5'],
 '0001193125-14-018634': ['#tx635047_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312514018634/d635047d10q.htm#tx635047_5'],
 '0001193125-13-409855': ['#tx594455_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312513409855/d594455d10q.htm#tx594455_5'],
 '0001193125-13-310206': ['#tx527745_102',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312513310206/d527745d10k.htm#tx527745_102'],
 '0001193125-13-160748': ['#tx497226_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312513160748/d497226d10q.htm#tx497226_5'],
 '0001193125-13-022207': ['#tx453668_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312513022207/d453668d10q.htm#tx453668_5']}

In [ ]:
print( [txt for acc_num,  txt in Accession_Number_URL.items() if 21 > int(acc_num.split(sep='-')[1]) > 16] )

In [ ]:
# Post-2016 uses the following .txt links. 
Accession_Number_URL_16_20 = {'0001564590-20-019706': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459020019706/0001564590-20-019706.txt'],
 '0001564590-20-002450': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459020002450/0001564590-20-002450.txt'],
 '0001564590-19-037549': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459019037549/0001564590-19-037549.txt'],
 '0001564590-19-027952': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459019027952/0001564590-19-027952.txt'],
 '0001564590-19-012709': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459019012709/0001564590-19-012709.txt'],
 '0001564590-19-001392': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459019001392/0001564590-19-001392.txt'],
 '0001564590-18-024893': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459018024893/0001564590-18-024893.txt'],
 '0001564590-18-019062': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459018019062/0001564590-18-019062.txt'],
 '0001564590-18-009307': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459018009307/0001564590-18-009307.txt'],
 '0001564590-18-001129': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459018001129/0001564590-18-001129.txt'],
 '0001564590-17-020171': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459017020171/0001564590-17-020171.txt'],
 '0001564590-17-014900': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459017014900/0001564590-17-014900.txt'],
 '0001564590-17-007547': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459017007547/0001564590-17-007547.txt'],
 '0001564590-17-000654': ['https://www.sec.gov/Archives/edgar/data/0000789019/000156459017000654/0001564590-17-000654.txt']}

In [15]:
# AN of new anchor tag - 'id. 
print("Anchor tag chamge from 'name' to 'id' for the following Accession Number: \n")
list_AN_Active = list(AN_Active.keys())
list_AN_Active.reverse() 
name_to_id = list_AN_Active[-3:]
print(f'{name_to_id} \n')

print("Assuming all new filings are 'id' tagged.")

Anchor tag chamge from 'name' to 'id' for the following Accession Number:

['0001564590-19-037549', '0001564590-20-002450', '0001564590-20-019706']

Assuming all new filings are 'id' tagged.

In [ ]:

#TESTING

AN_Active = {'0001193125-16-742796' : [ '#tx245252_5' , 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312516742796/d245252d10q.htm#tx245252_5' ]}

# 2016 onwards. Use the above Accession_Number_URL_16_20, 2016+ need to use .txt format. 
for AN, key_url in AN_Active.items():
    
    # Break is needed to limit lower bound, either 
    # pre-2016 = 0001193125-12-170665 (if excludes -12-170665 ) or 
    # post-16 = 0001193125-16-742796 (x > 16, excludes 16)
    print('~'*75)

    # if statement takes in Acc-Num: xx-xxx-xx
    if AN == '0001193125-12-170665':
        break

    if int( AN.split( sep='-' )[1] ) < 17:
        
        print(f'Accession Number - {AN}\n')
        key = key_url[0]
        print(f'key - {key_url[0]}\n')
        act_url = key_url[1]
        print(f'Active URL - {key_url[1]}\n')
        
        r = requests.get(act_url)
        soup = BeautifulSoup(r.content, "lxml")

        filing_document = soup.find('document')
        page_key = soup.find_all(attrs={"name": "{}".format(key.replace('#', ''))})

        document_id = filing_document.type.find(text=True, recursive=False).strip()
        print('page_key - ', page_key)
        T_table = [ table.parent.parent.parent.next_sibling.next_sibling.next_sibling.next_sibling for table in page_key ]
        print(T_table)

In [24]:
AN_active_test = {
    '0001564590-17-000654': ['#BALANCE_SHEETS',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000156459017000654/msft-10q_20161231.htm#BALANCE_SHEETS'],
    '0001193125-16-742796': ['#tx245252_5',
  'https://www.sec.gov/Archives/edgar/data/0000789019/000119312516742796/d245252d10q.htm#tx245252_5'],}

In [27]:
Checklist ={}

# 2016 onwards. Use the above Accession_Number_URL_16_20, 2016+ need to use .txt format. 
for AN, key_url in AN_Active.items():
    
    # Break is needed to limit lower bound, either 
    # pre-2016 = 0001193125-12-170665 (if excludes -12-170665 ) or 
    # post-16 = 0001193125-16-742796 (x > 16, excludes 16)
    print('~'*75)

    # if statement takes in Acc-Num: xx-xxx-xx
    if AN == '0001193125-12-170665':
        break
    
    # For filings prior to 16, use key-tag.
    if int( AN.split( sep='-' )[1] ) < 17:
        
        print(f'Accession Number - {AN}\n')
        key = key_url[0]
        print(f'key - {key_url[0]}\n')
        act_url = key_url[1]
        print(f'Active URL - {key_url[1]}\n')
        
        r = requests.get(act_url)
        soup = BeautifulSoup(r.content, "lxml")

        filing_document = soup.find('document')
        page_key = soup.find_all(attrs={"name": "{}".format(key.replace('#', ''))})

        document_id = filing_document.type.find(text=True, recursive=False).strip()

        T_table = [ table.parent.parent.parent.next_sibling.next_sibling.next_sibling.next_sibling for table in page_key ]
#         print(T_table)
    
    # For Filings after 2016, use 'name' & 'id' anchor tags.
    if int( AN.split( sep='-' )[1] ) > 16:
        
        # Take the AN in Accession_Number_URL
        url_txt = Accession_Number_URL[AN]
        print(url_txt)
        
        r = requests.get(url_txt)
        soup = BeautifulSoup(r.content, "lxml")

        filing_document = soup.find('document')
        
        document_id = filing_document.type.find(text=True, recursive=False).strip()
        
        # For filings starting from 2020, attr: 'name' change to 'id'
        if AN in name_to_id:
            page_key = soup.find_all(attrs={"id": "BALANCE_SHEETS"})

            T_table = [table.next_sibling.next_sibling.next_sibling.next_sibling for table in page_key ]
            # print(T_table)

        else:
            page_key = soup.find_all(attrs={"name": "BALANCE_SHEETS"})

            T_table = [ page_key[0].parent.next_sibling.next_sibling.next_sibling.next_sibling ]

    target = T_table[0].findAll('tr')
    row_list = [ row for row in target if row.get_text(strip=True, separator=',') != '']

    col_list = []

    for row in row_list:
        col = row.find_all('td')
        column = []
        for tr in col:
            ele = tr.text
            
            try:
                ele= ele.encode('cp1252').decode("utf-8", "ignore")
            except:
                ele.encode('latin1').decode("utf-8", "ignore")
                
            column.append(ele)
        col_list.append(column)

    col_list.pop(0)

    new_col_list = []
    for col_num, column in enumerate(col_list): 

        if col_num == 0:
#             print('raw column - ', column)
            Q, Y = Quarter(column)
#             print(Q, Y)
            new_col_list.append(Q)
            new_col_list.append(Y)

        else:
            column.pop(1)
            column.pop(1)

            new_col_list.append(cleaning_column( column ))

    df = pd.DataFrame(new_col_list)
    df = df.T.reset_index(drop=True)
    df.columns = df.iloc[0]
    df = df.drop([row for row in range(df.shape[0]) if row != 1], axis=0).reset_index(drop=True)
    ICD.display(df)

    try: 
        with open('{}-{}.csv'.format(AN, document_id), "wb") as fp:   # Pickling
            pickle.dump(df, fp)

        # display a status to the user.
        print('All the pages from {} document {} have been tableized and saved.'.format(AN, document_id))

    except:
        Checklist.update( f'{document_id} : {AN}' )
        print("Can't save file {}, file type - {}".format(AN, document_id))
        
    print('-'*80) 

if Checklist == {}:
    print('\nEverything went well.\n')
    
else: 
    print('\nThese files have a problem.\n', Checklist)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459020019706/0001564590-20-019706.txt
raw column -  ['\n', '\n', '\nMarch 31,2020', '\n', '\n', '\nJune30,2019', '\n']
column used for quarter ['\n', '\n', '\nMarch 31,2020', '\n', '\n', '\nJune30,2019', '\n']
new_column used for year ['March', '31,2020', 'June30,2019']
Q ['Q1', 'Q2']
['Quarter', 'Q1'] ['Year', '2020']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other current assets,Total current assets,Property and Equipment,Operating lease right of use assets,Equity investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Current portion of long term debt,Accrued compensation,Short term income taxes,Short term unearned revenue,Other current liabilities,Total current liabilities,Long term debt,Long term income taxes,Long term unearned revenue,Deferred income taxes,Operating lease liabilities,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q1,2020,None,None,11710000000,125916000000,137626000000,22699000000,1644000000,8536000000,170505000000,41221000000,8448000000,2660000000,42064000000,6855000000,13696000000,285449000000,None,None,9246000000,3748000000,6254000000,3296000000,27012000000,9151000000,58707000000,62862000000,28888000000,3385000000,185000000,7248000000,9673000000,170948000000,None,None,79813000000,32012000000,2676000000,114501000000,285449000000

All the pages from 0001564590-20-019706 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459020002450/0001564590-20-002450.txt
raw column -  ['\n', '\n', '\nDecember31,2019', '\n', '\n', '\nJune30,2019', '\n']
column used for quarter ['\n', '\n', '\nDecember31,2019', '\n', '\n', '\nJune30,2019', '\n']
new_column used for year ['December31,2019', 'June30,2019']
Q ['Q4', 'Q2']
['Quarter', 'Q4'] ['Year', '2019']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other current assets,Total current assets,Property and Equipment,Operating lease right of use assets,Equity investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Current portion of long term debt,Accrued compensation,Short term income taxes,Short term unearned revenue,Other current liabilities,Total current liabilities,Long term debt,Long term income taxes,Long term unearned revenue,Deferred income taxes,Operating lease liabilities,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive loss,Shareholder Equity,Total liabilities and equity
0,Q4,2019,None,None,8864000000,125389000000,134253000000,23525000000,1823000000,7473000000,167074000000,40522000000,8439000000,2755000000,42248000000,7126000000,14630000000,282794000000,None,None,8811000000,6247000000,5421000000,2687000000,27343000000,9131000000,59640000000,63361000000,28754000000,3878000000,222000000,7172000000,9658000000,172685000000,None,None,79625000000,30739000000,255000000,110109000000,282794000000

All the pages from 0001564590-20-002450 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459019037549/0001564590-19-037549.txt
raw column -  ['\n', '\n', '\nSeptember 30,2019', '\n', '\n', '\nJune 30,2019', '\n']
column used for quarter ['\n', '\n', '\nSeptember 30,2019', '\n', '\n', '\nJune 30,2019', '\n']
new_column used for year ['September', '30,2019', 'June', '30,2019']
Q ['Q3', 'Q2']
['Quarter', 'Q3'] ['Year', '2019']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other current assets,Total current assets,Property and Equipment,Operating lease right of use assets,Equity investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Current portion of long term debt,Accrued compensation,Short term income taxes,Short term unearned revenue,Other current liabilities,Total current liabilities,Long term debt,Long term income taxes,Long term unearned revenue,Deferred income taxes,Operating lease liabilities,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive loss,Shareholder Equity,Total liabilities and equity
0,Q3,2019,None,None,13117000000,123519000000,136636000000,19087000000,2622000000,7551000000,165896000000,38409000000,7890000000,2684000000,42113000000,7508000000,14455000000,278955000000,None,None,8574000000,3017000000,4676000000,3440000000,29904000000,8507000000,58118000000,66478000000,28457000000,4122000000,234000000,6659000000,8826000000,172894000000,None,None,78882000000,27240000000,61000000,106061000000,278955000000

All the pages from 0001564590-19-037549 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459019027952/0001564590-19-027952.txt
raw column -  ['\nJune 30,', '\n', '\n2019', '\n', '\n', '\n2018', '\n']
column used for quarter ['\nJune 30,', '\n', '\n2019', '\n', '\n', '\n2018', '\n']
new_column used for year ['June', '30,', '2019', '2018']
Q ['Q2']
['Quarter', 'Q2'] ['Year', '2019']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Operating lease right of use assets,Equity investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Current portion of long term debt,Accrued compensation,Short term income taxes,Short term unearned revenue,Other,Total current liabilities,Long term debt,Long term income taxes,Long term unearned revenue,Deferred income taxes,Operating lease liabilities,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive loss,Shareholder Equity,Total liabilities and equity
0,Q2,2019,None,None,11356000000,122463000000,133819000000,29524000000,2063000000,10146000000,175552000000,36477000000,7379000000,2649000000,42026000000,7750000000,14723000000,286556000000,None,None,9382000000,5516000000,6830000000,5665000000,32676000000,9351000000,69420000000,66662000000,29612000000,4530000000,233000000,6188000000,7581000000,184226000000,None,None,78520000000,24150000000,340000000,102330000000,286556000000

All the pages from 0001564590-19-027952 document 10-K have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459019012709/0001564590-19-012709.txt
raw column -  ['\n', '\n', '\nMarch 31,2019', '\n', '\n', '\nJune30,2018', '\n']
column used for quarter ['\n', '\n', '\nMarch 31,2019', '\n', '\n', '\nJune30,2018', '\n']
new_column used for year ['March', '31,2019', 'June30,2018']
Q ['Q1', 'Q2']
['Quarter', 'Q1'] ['Year', '2019']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Operating lease right of use assets,Equity investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Current portion of long term debt,Accrued compensation,Short term income taxes,Short term unearned revenue,Other,Total current liabilities,Long term debt,Long term income taxes,Long term unearned revenue,Deferred income taxes,Operating lease liabilities,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive loss,Shareholder Equity,Total liabilities and equity
0,Q1,2019,None,None,11212000000,120406000000,131618000000,19269000000,1951000000,7049000000,159887000000,33648000000,7121000000,2403000000,41861000000,8103000000,10258000000,263281000000,None,None,7544000000,6515000000,5764000000,1950000000,24251000000,7837000000,53861000000,66585000000,29514000000,3884000000,1838000000,5972000000,6763000000,168417000000,None,None,77791000000,18338000000,1265000000,94864000000,263281000000

All the pages from 0001564590-19-012709 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459019001392/0001564590-19-001392.txt
raw column -  ['\n', '\n', '\nDecember 31,2018', '\n', '\n', '\nJune30,2018', '\n']
column used for quarter ['\n', '\n', '\nDecember 31,2018', '\n', '\n', '\nJune30,2018', '\n']
new_column used for year ['December', '31,2018', 'June30,2018']
Q ['Q4', 'Q2']
['Quarter', 'Q4'] ['Year', '2018']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Operating lease right of use assets,Equity investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Current portion of long term debt,Accrued compensation,Short term income taxes,Short term unearned revenue,Other,Total current liabilities,Long term debt,Long term income taxes,Long term unearned revenue,Deferred income taxes,Operating lease liabilities,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive loss,Shareholder Equity,Total liabilities and equity
0,Q4,2018,None,None,6638000000,121024000000,127662000000,19680000000,1961000000,7571000000,156874000000,32717000000,6806000000,2274000000,41577000000,8482000000,10129000000,258859000000,None,None,7563000000,3516000000,4624000000,2033000000,24285000000,8297000000,50318000000,69653000000,29161000000,3799000000,2062000000,5683000000,6055000000,166731000000,None,None,77556000000,16585000000,2013000000,92128000000,258859000000

All the pages from 0001564590-19-001392 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459018024893/0001564590-18-024893.txt
raw column -  ['\n', '\n', '\nSeptember30,2018', '\n', '\n', '\nJune30,2018', '\n']
column used for quarter ['\n', '\n', '\nSeptember30,2018', '\n', '\n', '\nJune30,2018', '\n']
new_column used for year ['September30,2018', 'June30,2018']
Q ['Q3', 'Q2']
['Quarter', 'Q3'] ['Year', '2018']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Operating lease right of use assets,Equity investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Current portion of long term debt,Accrued compensation,Short term income taxes,Short term unearned revenue,Other,Total current liabilities,Long term debt,Long term income taxes,Long term unearned revenue,Deferred income taxes,Operating lease liabilities,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive loss,Shareholder Equity,Total liabilities and equity
0,Q3,2018,None,None,15137000000,120743000000,135880000000,17390000000,3614000000,7311000000,164195000000,31430000000,6734000000,2034000000,35855000000,7579000000,9792000000,257619000000,None,None,8511000000,6497000000,4271000000,2341000000,26704000000,7953000000,56277000000,69733000000,28936000000,3538000000,1977000000,5652000000,5539000000,171652000000,None,None,71303000000,17279000000,2615000000,85967000000,257619000000

All the pages from 0001564590-18-024893 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459018019062/0001564590-18-019062.txt
raw column -  ['\nJune 30,', '\n', '\n2018', '\n', '\n', '\n2017', '\n']
column used for quarter ['\nJune 30,', '\n', '\n2018', '\n', '\n', '\n2017', '\n']
new_column used for year ['June', '30,', '2018', '2017']
Q ['Q2']
['Quarter', 'Q2'] ['Year', '2018']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Operating lease right of use assets,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Short term income taxes,Short term unearned revenue,Other,Total current liabilities,Long term debt,Long term income taxes,Long term unearned revenue,Deferred income taxes,Operating lease liabilities,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q2,2018,None,None,11946000000,121822000000,133768000000,26481000000,2662000000,6751000000,169662000000,29460000000,6686000000,1862000000,35683000000,8053000000,7442000000,258848000000,None,None,8617000000,0,3998000000,6103000000,2121000000,28905000000,8744000000,58488000000,72242000000,30265000000,3815000000,541000000,5568000000,5211000000,176130000000,None,None,71223000000,13682000000,2187000000,82718000000,258848000000

All the pages from 0001564590-18-019062 document 10-K have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459018009307/0001564590-18-009307.txt
raw column -  ['\n', '\n', '\nMarch 31,2018', '\n', '\n', '\nJune30,2017', '\n']
column used for quarter ['\n', '\n', '\nMarch 31,2018', '\n', '\n', '\nJune30,2017', '\n']
new_column used for year ['March', '31,2018', 'June30,2017']
Q ['Q1', 'Q2']
['Quarter', 'Q1'] ['Year', '2018']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Operating lease right of use assets,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Short term income taxes,Short term unearned revenue,Other,Total current liabilities,Long term debt,Long term income taxes,Long term unearned revenue,Deferred income taxes,Operating lease liabilities,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q1,2018,None,None,9221000000,123049000000,132270000000,17208000000,2084000000,5097000000,156659000000,27929000000,6859000000,2818000000,35582000000,8544000000,7106000000,245497000000,None,None,7623000000,230000000,3447000000,5149000000,814000000,21370000000,7500000000,46133000000,73480000000,30669000000,2585000000,2417000000,5751000000,5223000000,166258000000,None,None,70418000000,9974000000,1153000000,79239000000,245497000000

All the pages from 0001564590-18-009307 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459018001129/0001564590-18-001129.txt
raw column -  ['\n', '\n', '\nDecember 31,2017', '\n', '\n', '\nJune30,2017', '\n']
column used for quarter ['\n', '\n', '\nDecember 31,2017', '\n', '\n', '\nJune30,2017', '\n']
new_column used for year ['December', '31,2017', 'June30,2017']
Q ['Q4', 'Q2']
['Quarter', 'Q4'] ['Year', '2017']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Operating lease right of use assets,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Short term income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term income taxes,Long term unearned revenue,Deferred income taxes,Operating lease liabilities,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q4,2017,None,None,12859000000,129921000000,142780000000,18428000000,2003000000,4422000000,167633000000,26304000000,6749000000,3961000000,35355000000,9034000000,6967000000,256003000000,None,None,7850000000,12466000000,3446000000,4427000000,788000000,21309000000,26000000,7787000000,58099000000,73348000000,30050000000,2500000000,3186000000,5640000000,4820000000,177643000000,None,None,70192000000,8567000000,399000000,78360000000,256003000000

All the pages from 0001564590-18-001129 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459017020171/0001564590-17-020171.txt
raw column -  ['\n', '\n', '\nSeptember30,2017', '\n', '\n', '\nJune30,2017', '\n']
column used for quarter ['\n', '\n', '\nSeptember30,2017', '\n', '\n', '\nJune30,2017', '\n']
new_column used for year ['September30,2017', 'June30,2017']
Q ['Q3', 'Q2']
['Quarter', 'Q3'] ['Year', '2017']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Operating lease right of use assets,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Operating lease liabilities,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q3,2017,None,None,6884000000,131587000000,138471000000,14561000000,3211000000,4788000000,161031000000,24809000000,6844000000,5343000000,35389000000,9598000000,6083000000,249097000000,None,None,6866000000,8170000000,1050000000,4108000000,920000000,22778000000,203000000,7520000000,51615000000,76255000000,2126000000,5513000000,5768000000,18173000000,159450000000,None,None,69419000000,19702000000,526000000,89647000000,249097000000

All the pages from 0001564590-17-020171 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459017014900/0001564590-17-014900.txt
raw column -  ['\nJune30,', '\n', '\n2017', '\n', '\n', '\n2016', '\n']
column used for quarter ['\nJune30,', '\n', '\n2017', '\n', '\n', '\n2016', '\n']
new_column used for year ['June30,', '2017', '2016']
Q ['Q2']
['Quarter', 'Q2'] ['Year', '2017']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q2,2017,None,None,7663000000,125318000000,132981000000,19792000000,2181000000,4897000000,159851000000,23734000000,6023000000,35122000000,10106000000,6250000000,241086000000,None,None,7390000000,9072000000,1049000000,5819000000,718000000,34102000000,97000000,6280000000,64527000000,76073000000,10377000000,531000000,17184000000,168692000000,None,None,69315000000,2648000000,431000000,72394000000,241086000000

All the pages from 0001564590-17-014900 document 10-K have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459017007547/0001564590-17-007547.txt
raw column -  ['\n', '\n', '\nMarch31,2017', '\n', '\n', '\nJune30,2016', '\n']
column used for quarter ['\n', '\n', '\nMarch31,2017', '\n', '\n', '\nJune30,2016', '\n']
new_column used for year ['March31,2017', 'June30,2016']
Q ['Q1', 'Q2']
['Quarter', 'Q1'] ['Year', '2017']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q1,2017,None,None,6713000000,119305000000,126018000000,12882000000,1979000000,5434000000,146313000000,21962000000,7381000000,34668000000,10547000000,4146000000,225017000000,None,None,6217000000,7187000000,599000000,4604000000,654000000,26518000000,201000000,6025000000,52005000000,76222000000,9215000000,465000000,17381000000,155288000000,None,None,68554000000,531000000,644000000,69729000000,225017000000

All the pages from 0001564590-17-007547 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://www.sec.gov/Archives/edgar/data/0000789019/000156459017000654/0001564590-17-000654.txt
raw column -  ['\n', '\n', '\nDecember 31,2016', '\n', '\n', '\nJune30,2016', '\n']
column used for quarter ['\n', '\n', '\nDecember 31,2016', '\n', '\n', '\nJune30,2016', '\n']
new_column used for year ['December', '31,2016', 'June30,2016']
Q ['Q4', 'Q2']
['Quarter', 'Q4'] ['Year', '2016']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q4,2016,None,None,8468000000,114313000000,122781000000,14343000000,1961000000,5864000000,144949000000,21379000000,8912000000,34524000000,11001000000,3845000000,224610000000,None,None,6580000000,25065000000,599000000,3982000000,508000000,26085000000,1280000000,6688000000,70787000000,59306000000,8595000000,1133000000,15980000000,155801000000,None,None,68177000000,120000000,512000000,68809000000,224610000000

All the pages from 0001564590-17-000654 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-16-742796

key - #tx245252_5

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312516742796/d245252d10q.htm#tx245252_5

raw column -  ['', '', 'September30,2016', '', '', 'June30,2016', '']
column used for quarter ['', '', 'September30,2016', '', '', 'June30,2016', '']
new_column used for year ['September30,2016', 'June30,2016']
Q ['Q3', 'Q2']
['Quarter', 'Q3'] ['Year', '2016']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q3,2016,None,None,13928000000,123004000000,136932000000,11129000000,3122000000,6726000000,157909000000,19224000000,10486000000,17907000000,3522000000,3476000000,212524000000,None,None,6296000000,14536000000,3621000000,720000000,26304000000,210000000,7123000000,58810000000,60154000000,7284000000,1564000000,14340000000,142152000000,None,None,67747000000,944000000,1681000000,70372000000,212524000000

All the pages from 0001193125-16-742796 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-16-662209

key - #tx187868_27

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312516662209/d187868d10k.htm#tx187868_27

raw column -  ['June30,', '', '2016', '', '', '2015', '']
column used for quarter ['June30,', '', '2016', '', '', '2015', '']
new_column used for year ['June30,', '2016', '2015']
Q ['Q2']
['Quarter', 'Q2'] ['Year', '2016']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q2,2016,None,None,6510000000,106730000000,113240000000,18277000000,2251000000,5892000000,139660000000,18356000000,10431000000,17872000000,3733000000,3642000000,193694000000,None,None,6898000000,12904000000,0,5264000000,580000000,27468000000,294000000,5949000000,59357000000,40783000000,6441000000,1476000000,13640000000,121697000000,None,None,68178000000,2282000000,1537000000,71997000000,193694000000

All the pages from 0001193125-16-662209 document 10-K have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-16-550254

key - #tx256147_5

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312516550254/d256147d10q.htm#tx256147_5

raw column -  ['', '', ' March31, 2016', '', '', 'June30,2015', '']
column used for quarter ['', '', ' March31, 2016', '', '', 'June30,2015', '']
new_column used for year ['March31,', '2016', 'June30,2015']
Q ['Q1', 'Q2']
['Quarter', 'Q1'] ['Year', '2016']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q1,2016,None,None,7170000000,98382000000,105552000000,12247000000,2450000000,1574000000,6598000000,128421000000,16831000000,11315000000,17948000000,4459000000,2895000000,181869000000,None,None,6759000000,5498000000,0,4276000000,685000000,20876000000,373000000,5887000000,44354000000,40896000000,5017000000,2674000000,14122000000,107063000000,None,None,68012000000,4954000000,1840000000,74806000000,181869000000

All the pages from 0001193125-16-550254 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-16-441821

key - #tx15167_5

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312516441821/d15167d10q.htm#tx15167_5

raw column -  ['', '', ' December31, 2015', '', '', 'June30,2015', '']
column used for quarter ['', '', ' December31, 2015', '', '', 'June30,2015', '']
new_column used for year ['December31,', '2015', 'June30,2015']
Q ['Q4', 'Q2']
['Quarter', 'Q4'] ['Year', '2015']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q4,2015,None,None,7185000000,95455000000,102640000000,14507000000,2702000000,1618000000,6345000000,127812000000,15789000000,11514000000,17436000000,4619000000,2928000000,180098000000,None,None,6936000000,3000000000,750000000,3649000000,493000000,20929000000,439000000,6447000000,42643000000,40679000000,4102000000,2194000000,13700000000,103318000000,None,None,68279000000,6728000000,1773000000,76780000000,180098000000

All the pages from 0001193125-16-441821 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-15-350718

key - #tx83804_5

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312515350718/d83804d10q.htm#tx83804_5

raw column -  ['', '', 'September30,2015', '', '', 'June30,2015', '']
column used for quarter ['', '', 'September30,2015', '', '', 'June30,2015', '']
new_column used for year ['September30,2015', 'June30,2015']
Q ['Q3', 'Q2']
['Quarter', 'Q3'] ['Year', '2015']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q3,2015,None,None,5431000000,93924000000,99355000000,11444000000,3816000000,1447000000,5594000000,121656000000,15046000000,11438000000,17142000000,4745000000,2869000000,172896000000,None,None,6630000000,9998000000,750000000,3450000000,607000000,21603000000,154000000,6207000000,49399000000,27819000000,2784000000,2169000000,13280000000,95451000000,None,None,68093000000,7614000000,1738000000,77445000000,172896000000

All the pages from 0001193125-15-350718 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-15-272806

key - #tx918813_32

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312515272806/d918813d10k.htm#tx918813_32

raw column -  ['June30,', '', '2015', '', '', '2014', '']
column used for quarter ['June30,', '', '2015', '', '', '2014', '']
new_column used for year ['June30,', '2015', '2014']
Q ['Q2']
['Quarter', 'Q2'] ['Year', '2015']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q2,2015,None,None,5595000000,90931000000,96526000000,17908000000,2902000000,1915000000,5461000000,124712000000,14731000000,12053000000,16939000000,4835000000,2953000000,176223000000,None,None,6591000000,4985000000,2499000000,5096000000,606000000,23223000000,92000000,6766000000,49858000000,27808000000,2095000000,2835000000,13544000000,96140000000,None,None,68465000000,9096000000,2522000000,80083000000,176223000000

All the pages from 0001193125-15-272806 document 10-K have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-15-144151

key - #tx860721_5

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312515144151/d860721d10q.htm#tx860721_5

raw column -  ['', '', 'March31,2015', '', '', 'June30,2014', '']
column used for quarter ['', '', 'March31,2015', '', '', 'June30,2014', '']
new_column used for year ['March31,2015', 'June30,2014']
Q ['Q1', 'Q2']
['Quarter', 'Q1'] ['Year', '2015']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q1,2015,None,None,7414000000,88024000000,95438000000,12427000000,2469000000,1688000000,6376000000,118398000000,14375000000,12019000000,21728000000,6963000000,3200000000,176683000000,None,None,6690000000,1725000000,2499000000,3902000000,758000000,18232000000,96000000,6846000000,40748000000,27644000000,1966000000,2919000000,13274000000,86551000000,None,None,68475000000,18186000000,3471000000,90132000000,176683000000

All the pages from 0001193125-15-144151 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-15-020351

key - #tx827041_5

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312515020351/d827041d10q.htm#tx827041_5

raw column -  ['', '', 'December31,2014', '', '', 'June30,2014', '']
column used for quarter ['', '', 'December31,2014', '', '', 'June30,2014', '']
new_column used for year ['December31,2014', 'June30,2014']
Q ['Q4', 'Q2']
['Quarter', 'Q4'] ['Year', '2014']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q4,2014,None,None,6426000000,83823000000,90249000000,16186000000,2053000000,1701000000,6173000000,116362000000,13607000000,12665000000,21855000000,7299000000,3060000000,174848000000,None,None,6932000000,8299000000,1749000000,3479000000,711000000,19192000000,430000000,6623000000,47415000000,18260000000,2051000000,2820000000,12423000000,82969000000,None,None,68765000000,19731000000,3383000000,91879000000,174848000000

All the pages from 0001193125-15-020351 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-14-380252

key - #tx770268_5

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312514380252/d770268d10q.htm#tx770268_5

raw column -  [' September30, 2014', '', '', 'June30,2014', '']
column used for quarter [' September30, 2014', '', '', 'June30,2014', '']
new_column used for year ['September30,', '2014', 'June30,2014']
Q ['Q3', 'Q2']
['Quarter', 'Q3'] ['Year', '2014']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q3,2014,None,None,6302000000,82891000000,89193000000,12887000000,3141000000,1784000000,5434000000,112439000000,13229000000,13943000000,20081000000,6693000000,3271000000,169656000000,None,None,6769000000,3500000000,1748000000,3740000000,903000000,20713000000,191000000,7130000000,44694000000,18472000000,1825000000,2714000000,11781000000,79486000000,None,None,68362000000,18051000000,3757000000,90170000000,169656000000

All the pages from 0001193125-14-380252 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-14-289961

key - #tx722626_27

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312514289961/d722626d10k.htm#tx722626_27

raw column -  ['June30,', '', '2014', '', '', '2013', '']
column used for quarter ['June30,', '', '2014', '', '', '2013', '']
new_column used for year ['June30,', '2014', '2013']
Q ['Q2']
['Quarter', 'Q2'] ['Year', '2014']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q2,2014,None,None,8669000000,77040000000,85709000000,19544000000,2660000000,1941000000,4392000000,114246000000,13011000000,14597000000,20127000000,6981000000,3422000000,172384000000,None,None,7432000000,2000000000,0,4797000000,782000000,23150000000,558000000,6906000000,45625000000,20645000000,2008000000,2728000000,11594000000,82600000000,None,None,68366000000,17710000000,3708000000,89784000000,172384000000

All the pages from 0001193125-14-289961 document 10-K have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-14-157088

key - #tx695543_5

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312514157088/d695543d10q.htm#tx695543_5

raw column -  ['', '', 'March31,2014', '', '', 'June30,2013', '']
column used for quarter ['', '', 'March31,2014', '', '', 'June30,2013', '']
new_column used for year ['March31,2014', 'June30,2013']
Q ['Q1', 'Q2']
['Quarter', 'Q1'] ['Year', '2014']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q1,2014,None,None,11572000000,76853000000,88425000000,13497000000,1920000000,1424000000,3740000000,109006000000,11771000000,14792000000,14751000000,2901000000,2898000000,156119000000,None,None,4583000000,2000000000,3887000000,694000000,17670000000,794000000,4275000000,33903000000,20679000000,1842000000,2318000000,9953000000,68695000000,None,None,67803000000,16289000000,3332000000,87424000000,156119000000

All the pages from 0001193125-14-157088 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-14-018634

key - #tx635047_5

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312514018634/d635047d10q.htm#tx635047_5

raw column -  [' December31, 2013', '', '', 'June30,2013', '']
column used for quarter [' December31, 2013', '', '', 'June30,2013', '']
new_column used for year ['December31,', '2013', 'June30,2013']
Q ['Q4', 'Q2']
['Quarter', 'Q4'] ['Year', '2013']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q4,2013,None,None,10059000000,73885000000,83944000000,15986000000,1594000000,1328000000,4018000000,106870000000,11567000000,14607000000,14680000000,2945000000,2874000000,153543000000,None,None,5398000000,300000000,2000000000,3169000000,591000000,17616000000,748000000,3920000000,33742000000,20676000000,1858000000,2377000000,9790000000,68443000000,None,None,67476000000,14347000000,3277000000,85100000000,153543000000

All the pages from 0001193125-14-018634 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-13-409855

key - #tx594455_5

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312513409855/d594455d10q.htm#tx594455_5

raw column -  [' September30, 2013', '', '', 'June30,2013', '']
column used for quarter [' September30, 2013', '', '', 'June30,2013', '']
new_column used for year ['September30,', '2013', 'June30,2013']
Q ['Q3', 'Q2']
['Quarter', 'Q3'] ['Year', '2013']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Short term debt,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q3,2013,None,None,4023000000,76649000000,80672000000,11007000000,2613000000,1258000000,3900000000,99450000000,10774000000,11995000000,14667000000,2982000000,2480000000,142348000000,None,None,4841000000,1300000000,2000000000,2856000000,834000000,18585000000,582000000,3625000000,34623000000,12632000000,1629000000,2236000000,9587000000,60707000000,None,None,67230000000,11680000000,2731000000,81641000000,142348000000

All the pages from 0001193125-13-409855 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-13-310206

key - #tx527745_102

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312513310206/d527745d10k.htm#tx527745_102

raw column -  ['June30,', '', '2013', '', '', '2012', '']
column used for quarter ['June30,', '', '2013', '', '', '2012', '']
new_column used for year ['June30,', '2013', '2012']
Q ['Q2']
['Quarter', 'Q2'] ['Year', '2013']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q2,2013,None,None,3804000000,73218000000,77022000000,17486000000,1938000000,1632000000,3388000000,101466000000,9991000000,10844000000,14655000000,3083000000,2392000000,142431000000,None,None,4828000000,2999000000,4117000000,592000000,20639000000,645000000,3597000000,37417000000,12601000000,1760000000,1709000000,10000000000,63487000000,None,None,67306000000,9895000000,1743000000,78944000000,142431000000

All the pages from 0001193125-13-310206 document 10-K have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-13-160748

key - #tx497226_5

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312513160748/d497226d10q.htm#tx497226_5

raw column -  [' March31, 2013', '', '', 'June30,2012', '']
column used for quarter [' March31, 2013', '', '', 'June30,2012', '']
new_column used for year ['March31,', '2013', 'June30,2012']
Q ['Q1', 'Q2']
['Quarter', 'Q1'] ['Year', '2013']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q1,2013,None,None,5240000000,69243000000,74483000000,11991000000,2133000000,1676000000,3241000000,93524000000,9204000000,11193000000,14682000000,3240000000,2262000000,134105000000,None,None,4532000000,2246000000,3474000000,689000000,16511000000,564000000,3913000000,31929000000,11949000000,1394000000,2424000000,9721000000,57417000000,None,None,66826000000,7657000000,2205000000,76688000000,134105000000

All the pages from 0001193125-13-160748 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Accession Number - 0001193125-13-022207

key - #tx453668_5

Active URL - https://www.sec.gov/Archives/edgar/data/0000789019/000119312513022207/d453668d10q.htm#tx453668_5

raw column -  [' December31,\n2012', '  ', '', '', 'June30,2012', '']
column used for quarter [' December31,\n2012', '  ', '', '', 'June30,2012', '']
new_column used for year ['December31,', '2012', 'June30,2012']
Q ['Q4', 'Q2']
['Quarter', 'Q4'] ['Year', '2012']

,Quarter,Year,Assets,Current assets,Cash,Short term investments,Total cash,Accounts Receivable,Inventory,Deferred income taxes,Other,Total current assets,Property and Equipment,Equity and other investments,Goodwill,Intangible assets,Other long term assets,Total assets,Shareholder Equity,Current liabilities,Accounts payable,Current portion of long term debt,Accrued compensation,Income taxes,Short term unearned revenue,Securities lending payable,Other,Total current liabilities,Long term debt,Long term unearned revenue,Deferred income taxes,Other long term liabilities,Total liabilities,Commitments and contingencies,Shareholder Equity,Common Stock,Retained Earnings,Accumulated other comprehensive income,Shareholder Equity,Total liabilities and equity
0,Q4,2012,None,None,6017000000,62295000000,68312000000,14317000000,1661000000,1983000000,3301000000,89574000000,8698000000,10707000000,14727000000,3341000000,1636000000,128683000000,None,None,4356000000,2241000000,2942000000,630000000,18354000000,21000000,3366000000,31910000000,11947000000,1459000000,2394000000,8397000000,56107000000,None,None,66334000000,4236000000,2006000000,72576000000,128683000000

All the pages from 0001193125-13-022207 document 10-Q have been tableized and saved.
--------------------------------------------------------------------------------

Everything went well.

##### 2017- 2020 working material

In [ ]:
type(column[0])

In [ ]:
url = 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459019012709/0001564590-19-012709.txt'
r = requests.get(url)
soup = BeautifulSoup(r.content, "html.parser")

page_key = soup.find_all(attrs={"name": "BALANCE_SHEETS"})
    
T_table = [page_key[0].parent.next_sibling.next_sibling.next_sibling.next_sibling ]
target = T_table[0].findAll('tr')
print(target)

In [ ]:
page_key

In [ ]:
print([row for row in range(df.shape[0]) if row != 1])

In [ ]:
[table.next_sibling.next_sibling.next_sibling.next_sibling for table in page_key ]

In [ ]:
T_table = [ table.next_sibling.next_sibling.children for table in page_key ]
print(T_table)

## End 2017-2020

In [ ]:
# Show Accession_Number_URL
Accession_Number_URL

## 2012 -2016

### Creating the .htm urls to get key.

In [ ]:
AN_Active = {}
# Get filename, method 3, use htm.# anchor to jump to Balnce sheet.
for AN, url in Accession_Number_URL.items():
    
    # Break is needed to limit lower bound, either 
    # pre-2016 = 0001193125-12-170665 (if excludes -12-170665 ) or 
    # post-16 = 0001193125-16-742796 (x > 16, excludes 16)
    
    # if statement takes in Acc-Num: xx-xxx-xx
    if AN == '0001193125-12-170665':
        break
        
    if int( AN.split( sep='-' )[1] ) < 17:
        print('~'*75)
        r = requests.get(url)
        
        try: 
            soup = BeautifulSoup(r.content, "html")
            
        except:
            print('Look at: ')
            print( '{} - {}'.format(AN, url))
            
        # 1.0
        AccessionNumber = AN.replace('-', '')
        
        # 2.1 part of table website.
        filename = str(soup.find('filename').contents[0]).replace('\n', '')
        print('filename - ', filename, '\n')
        
        # 2.2 Anchor page_key.
        hr_tag = soup.findAll('a', href=True)
        page_key = str( [table.get('href') for table in hr_tag if 'Balance Sheets' in table.get_text()][0])
        print('page_key - ', page_key, '\n')
        
        KEY = filename + page_key
        
        active_url = new_doc_url.format( xx = AccessionNumber, yy = KEY ).replace('.txt', '')

        print('active_url - ', active_url)
        
        # Key for 2016 onwards is the same, will overwrite the keys() in AN_Active. 
        AN_Active.update({ page_key : [active_url, AN]})

    else:
        continue

##### 2012- 2016 working material

AN_Active = {
 '0001193125-16-742796': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312516742796/0001193125-16-742796.txt'],
 '0001193125-16-662209': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312516662209/0001193125-16-662209.txt'],
 '0001193125-16-550254': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312516550254/0001193125-16-550254.txt'],
 '0001193125-16-441821': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312516441821/0001193125-16-441821.txt'],
 '0001193125-15-350718': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312515350718/0001193125-15-350718.txt'],
 '0001193125-15-272806': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312515272806/0001193125-15-272806.txt'],
 '0001193125-15-144151': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312515144151/0001193125-15-144151.txt'],
 '0001193125-15-020351': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312515020351/0001193125-15-020351.txt'],
 '0001193125-14-380252': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312514380252/0001193125-14-380252.txt'],
 '0001193125-14-289961': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312514289961/0001193125-14-289961.txt'],
 '0001193125-14-157088': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312514157088/0001193125-14-157088.txt'],
 '0001193125-14-018634': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312514018634/0001193125-14-018634.txt'],
 '0001193125-13-409855': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312513409855/0001193125-13-409855.txt'],
 '0001193125-13-310206': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312513310206/0001193125-13-310206.txt'],
 '0001193125-13-160748': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312513160748/0001193125-13-160748.txt'],
 '0001193125-13-022207': ['https://www.sec.gov/Archives/edgar/data/0000789019/000119312513022207/0001193125-13-022207.txt']
}

In [ ]:
# Show AN_Active
AN_Active

In [ ]:
# Before 2017 AND After 0001193125-12-170665
for key, url_AN in AN_Active.items():
            
    AN = url_AN[1]
    url = url_AN[0]
    
    print('key - ', key)
    print('\n')
    print('Accession Number - ', AN)
    print('\n')
    print('Active URL - ', url)
    print('\n')
    
    r = requests.get(url)
    soup = BeautifulSoup(r.content, "lxml")

    filing_document = soup.find('document')
    page_key = soup.find_all(attrs={"name": "{}".format(key.replace('#', ''))})
    
    document_id = filing_document.type.find(text=True, recursive=False).strip()
        
    T_table = [ table.parent.parent.parent.next_sibling.next_sibling.next_sibling.next_sibling for table in page_key ]    
    # print('T_table - ', T_table)
    
    target = T_table[0].findAll('tr')
    row_list = [ row for row in target if row.get_text(strip=True, separator=',') != '']

    col_list = []

    for row in row_list:
        col = row.find_all('td')
        column = []
        for tr in col:
            ele = tr.text
            ele= ele.encode('latin1').decode("utf-8", "ignore")
            column.append(ele)
        col_list.append(column)

    col_list.pop(0)

    new_col_list = []
    for col_num, column in enumerate(col_list): 

        if col_num == 0:
            print(column)
            Q, Y = Quarter(column)
            print(Q, Y)
            new_col_list.append(Q)
            new_col_list.append(Y)

        else:
            new_col_list.append(cleaning_column(column))

    df = pd.DataFrame(new_col_list)
    
    df = df.T.reset_index(drop=True)
    df.columns = df.iloc[0]
    df = df.drop([0,2], axis=0).reset_index(drop=True)
    ICD.display(df)

    try: 
        with open('{}-{}.csv'.format(AN, document_id), "wb") as fp:   # Pickling
            pickle.dump(df, fp)

        # display a status to the user.
        print('All the pages from {} document {} have been tableized and saved.'.format(AN, document_id))

    except:
        value_list.append(vv)
        print("Can't save file {}, file type = {}".format(AN, document_id))

        print('-'*80)

# New Method try 2016 and before, reference material ->

In [ ]:
# Got the key 
test_url = 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312516662209/d187868d10k.htm#tx187868_27'

r = requests.get(test_url)
soup = BeautifulSoup(r.content, "html")

hr_tag = soup.findAll('a', href=True)
list_of_table_in_page = [table.get('href') for table in hr_tag if 'Balance Sheets' in table.get_text() ][0]
print(list_of_table_in_page)

page_key = soup.find_all(attrs={"name": "tx187868_27"})
# add this to table below -> .findAll('tr')
T_table = [ table.parent.parent.parent.next_sibling.next_sibling.next_sibling.next_sibling for table in page_key ]
print(T_table)

# Figuring out how to use the key.

In [ ]:
def has_key(name):
    if  re.compile("#tx245252_5").search(name):
        return name

In [ ]:
test_url = 'https://www.sec.gov/Archives/edgar/data/0000789019/000119312516742796/0001193125-16-742796.txt'

r = requests.get(test_url)
soup = BeautifulSoup(r.content, "lxml")

page_key = soup.find_all(attrs={"name": "tx245252_5"})

T_table = [ table.parent.parent.parent.next_sibling.next_sibling.next_sibling.next_sibling for table in page_key ]

In [ ]:
page_key

In [ ]:
target = T_table[0].findAll('tr')
print(target)

In [ ]:
type(target)

In [ ]:
row_list = [ row for row in target if row.get_text(strip=True, separator=',') != '']
print(row_list)

In [ ]:
col_list = []
for row in row_list:
    col = row.find_all('td')
    column = []
    for tr in col:
        ele = tr.get_text()
        ele= ele.encode('latin1').decode('cp1252')
        column.append(ele)
    col_list.append(column)
    
print(col_list)

In [ ]:
col_list.pop(0)

In [ ]:
new_col_list = []
for col_num, column in enumerate(col_list): 
    
    if col_num == 0:
        print(column)
        Q, Y = Quarter(column)
        print(Q, Y)
        new_col_list.append(Q)
        new_col_list.append(Y)
        
    else:
        new_col_list.append(cleaning_column(column))

In [ ]:
new_col_list

In [ ]:
df = pd.DataFrame(new_col_list)
df = df.T.reset_index(drop=True)
df

In [ ]:
df.columns = df.iloc[0]
df = df.drop([0,2], axis=0).reset_index(drop=True)

## End of old reference material

# < TESTING AREA>

In [ ]:
# url = 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459020019706/msft-10q_20200331.htm#BALANCE_SHEETS'
url = 'https://www.sec.gov/Archives/edgar/data/0000789019/000156459020019706/0001564590-20-019706.txt'
key = '0001564590-20-019706'

In [ ]:
r = requests.get(url)
soup = BeautifulSoup(r.content, "lxml")

filing_document = soup.find('document')
document_id = filing_document.type.find(text=True, recursive=False).strip()

if key in list(Accession_Number_URL_16_20.keys())[0:3]:
    page_key = soup.find_all(attrs={"id": "BALANCE_SHEETS"})

    T_table = [table.next_sibling.next_sibling.next_sibling.next_sibling for table in page_key ]
    # print(T_table)

else:
    page_key = soup.find_all(attrs={"name": "BALANCE_SHEETS"})

    T_table = [ page_key[0].parent.next_sibling.next_sibling.next_sibling.next_sibling ]

target = T_table[0].findAll('tr')
row_list = [ row for row in target if row.get_text(strip=True, separator=',') != '']

col_list = []

for row in row_list:
    col = row.find_all('td')
    column = []
    for tr in col:
        ele = tr.text
        ele= ele.encode('cp1252').decode("utf-8", "ignore")
        column.append(ele)
    col_list.append(column)

col_list.pop(0)

new_col_list = []
for col_num, r_column in enumerate(col_list): 

    if col_num == 0:
        print('raw column - ', r_column)
        Q, Y = Quarter(r_column)
        print(Q, Y)
        new_col_list.append(Q)
        new_col_list.append(Y)

    else:
        
        new_col_list.append(cleaning_column( r_column ))

df = pd.DataFrame(new_col_list)
df = df.T.reset_index(drop=True)
df.columns = df.iloc[0]
df = df.drop([row for row in range(df.shape[0]) if row != 1], axis=0).reset_index(drop=True)
ICD.display(df)

In [ ]:
new_dict = [name for name in df.columns]
print(new_dict, len(new_dict))

In [ ]:
old_if = [name for name in df.columns]
print(old_if, len(old_if))

In [ ]:
import collections
print([item for item, count in collections.Counter(old_if).items() if count > 1])

In [ ]:
print(set(old_if) - set(new_dict), '\n')
print(set(new_dict) - set(old_if))

# </END TESTING AREA>

#                     {Nexted Function Territory}
## Take care of the multiplier in cleaning_column() and else where
## Limit: slow, not lean, ineffcient, relied heavily on indices (position in a list).

In [ ]:
QorK = {'10-Q' : [],
        '10-K' : []
       }

for acc_num, url in Accession_Number_URL.items():
    
    master_document_dict = {}
    
    # create a stop point
    if acc_num == '0001193125-16-742796':
        break

    else:
        
        # grab the response
        response = requests.get(url[0])

    # Soupify
        # pass it through the parser, in this case let's just use lxml because the tags seem to follow xml.
        soup = BeautifulSoup(response.content, 'lxml')
        filing_document = soup.find('document')
        
    # Parsing
        # Document type ->> document_id
        document_id = filing_document.type.find(text=True, recursive=False).strip()
        # Document sequence ->> document_sequence
        document_sequence = filing_document.sequence.find(text=True, recursive=False).strip()
        # Document filename ->> document_filename
        document_filename = filing_document.filename.find(text=True, recursive=False).strip()
        # Document description ->> document_description
        document_description = filing_document.description.find(text=True, recursive=False).strip()
        
    # Storage    
        # initalize our document dictionary
        master_document_dict[document_id] = {}

        # add the different parts, we parsed up above.
        master_document_dict[document_id]['document_sequence'] = document_sequence
        master_document_dict[document_id]['document_filename'] = document_filename
        master_document_dict[document_id]['document_description'] = document_description
        
# Scraping
        # grab the text portion of the document, this will be used to split the document into pages.
        filing_doc_text = filing_document.find('text').extract()

        # find all the thematic breaks, these help define page numbers and page breaks.
        all_thematic_breaks = filing_doc_text.find_all('table')

        # Locate and store page number via list comprehension.
        all_page_numbers = [thematic_break.previous_sibling for thematic_break in all_thematic_breaks if len(str(thematic_break))>6]
            
        # convert all thematic breaks to a string so it can be used for parsing
        all_thematic_breaks = [str(thematic_break) for thematic_break in all_thematic_breaks]

        # prep the document text for splitting, this means converting it to a string.
        filing_doc_string = str(filing_doc_text)
    
        # handle the case where there are thematic breaks.
        if len(all_thematic_breaks) > 0: 

            # define the regex delimiter pattern, this would just be all of our thematic breaks.
            regex_delimiter_pattern = '|'.join(map(re.escape, all_thematic_breaks))

            # split the document along each thematic break.
            split_filing_string = re.split(regex_delimiter_pattern, filing_doc_string)

            # store the document itself
            master_document_dict[document_id]['pages_code'] = split_filing_string

        # handle the case where there are no thematic breaks.
        elif len(all_thematic_breaks) == 0:

            # handles so it will display correctly.
            split_filing_string = all_thematic_breaks

            # store the document as is, since there are no thematic breaks. In other words, no splitting.
            master_document_dict[document_id]['pages_code'] = [filing_doc_string]
            
        # display some information to the user.
        print('-'*80)
        print('The document {} was parsed.'.format(document_id))
        print('There was {} page(s) found.'.format(len(all_page_numbers)))
        print('There was {} thematic breaks(s) found.'.format(len(all_thematic_breaks)))

        # store the documents in the master_filing_dictionary.
        master_filings_dict[acc_num]['filing_documents'] = master_document_dict
        
        # if document is 10-Q
        if document_id == '10-Q':
            QorK['10-Q'].append(acc_num) # add acc_num to QorK in 10-Q as key
        
        # if document is 10-K
        if document_id == '10-K':
            QorK['10-K'].append(acc_num) # add acc_num to QorK in 10-K as key
        
        del master_document_dict
        
        print('-'*80)
        print('All the documents for filing {} were parsed and stored.'.format(acc_num))

In [ ]:
string_test = master_filings_dict['0001193125-16-742796']['filing_documents']['10-Q']['pages_code']
for page_num, page in enumerate(string_test):
    if ('Cash and cash equivalents' in page) and ('Short-term investments' in page):
        print( string_test.index(page_num  + 3) )
        print('~'*40)
#string_test[56]
# df01 = table(string_test, '10-Q')
# df = df01[0]
# df

## Anchor Check Function

In [ ]:
# Variations of HTML anchors.
CBS_A = 'BALANCE SHEETS'
CBS_B = 'name="BALANCE_SHEETS"'
CBS_D = 'BALANCE SHEETS '
CBS_C = 'Cash and cash equivalents'
# SoO_A = '<a name="Statements_of_Operations"' 
# SoO_B = 'id="CONSOLIDATED_STATEMENTS_OPERATIONS"'
# SoO3 = 'name="CONSOLIDATED_STATEMENTS_OPERATIONS"'
# CSoO10K = 'name="Consolidated_Statements_of_Operations"'
# CSoO10Knew = 'id="Consolidated_Statements_of_Operations"'

# CF_A = '<a name="Statements_of_Cash'
# CF_B = 'id="CONSOLIDATED_STATEMENTS_CASH_FLOWS"'
# CF3 = 'name="CONSOLIDATED_STATEMENTS_CASH_FLOWS"'
# CCF10K = 'name="Consolidated_Statements_of_Cash_Flows"'
# CCF10Knew = 'id="Consolidated_Statements_of_Cash_Flows"'

def anchor_check(page_code):
    
    # if the page has one of these anchors
    if (CBS_A in page_code) or (CBS_B in page_code) or (CBS_D in page_code) and (CBS_C in page_code):
        return True

    #elif (SoO_A in page_code) or (SoO_B in page_code) or (SoO3 in page_code) or (CSoO10K in page_code) or (CSoO10Knew in page_code) :
        #return True

    #elif (CF_A in page_code) or (CF_B in page_code) or (CF3 in page_code) or (CCF10K in page_code) or (CCF10Knew in page_code):
        #return True


    else:
        return False

## Cleaning Columns and Cleaning Tables

In [ ]:
def table_extractor( page, multiplier, k ):
    
    # Convert string to BS object
    soup = BeautifulSoup(page, 'html5')

    # then get all the rows in the table.
    table_rows = soup.find_all('tr')
    
    if len( [tr.text for tr in table_rows[0].find_all('td')] ) < 3:
        del table_rows[0]
    
    single_table = []
    Date_column = []
    
    # Loop through each column, adding in three structures to single_table.
    for tr_post, tr in enumerate(table_rows):
        
        td = tr.find_all('td')

        column = [tr.text for tr in td]
        #print( 'tr_post', tr_post, len(column), column)
        # 10-Q 
        if k == '10-Q':
            
            if tr_post == 3:

                # Quarter Column
                col_Q, col_year = Quarter( column )
                single_table.append( col_Q )
                # Year Column
                single_table.append( col_year )

            elif tr_post > 4: 

                # Features Columns
                cleaned_data = cleaning_column( column , multiplier )
                if len(cleaned_data) > 10:
                    del cleaned_data[3]
                    
                single_table.append( cleaned_data )
                
        # 10-K
        elif k == '10-K':
            
#             if tr_post == 1 or tr_post == 2:
                    
#                 Date_column.append(column)
                
            if tr_post == 3:
                
                # Quarter Column
                col_date, col_year = Quarter(column)
                single_table.append( col_date )
                # Year Column
                single_table.append( col_year )
                
            elif tr_post > 4:              
                
                cleaned_data = cleaning_column( column , 10**6 )
                if len(cleaned_data) > 10:
                    del cleaned_data[3]
                
                single_table.append( cleaned_data )
            
    return single_table

In [ ]:
def df_clean( single_table ):
    print(single_table)
    table_df = pd.DataFrame(single_table)

    table_df = table_df.transpose()  
    print(table_df)
    table_df.drop(table_df.index[1:3], 0, inplace=True)

    #table_df.drop(table_df.index[2:], 0, inplace=True)

    table_df.columns = table_df.iloc[0]

    table_df = table_df.drop(table_df.index[0])
    
    return table_df

In [ ]:
def table(page_code, k):
    
    doc_tables=[]

    for page_post, page in enumerate(page_code):
        
        if ('(In millions) (Unaudited)' in page) and ('BALANCE SHEETS ' in page):
            
            single_table = table_extractor( page, 10**6, k )
            #print(single_table)
            table_df = df_clean(single_table)
                        
            doc_tables.append(table_df)
        
        elif ('BALANCE SHEETS ' in page) and ('(In thousands) (Unaudited)' in page):
            
            #print('page_post', page_post)
            
            single_table = table_extractor( page, 10**3, k )

            table_df = df_clean(single_table)

            doc_tables.append(table_df)
            
        else:
            print(page_post+1, 'anchor_check / in thousands/million problem')

                
    return doc_tables

# Exploring the Data

In [ ]:
explore_dict = {}
for QK, AccNum_list in QorK.items():
    
    #for an_postition, acc_num in enumerate(AccNum_list): 
    if QK== '10-Q':
        Q_new = AccNum_list[0]
        Q_old = AccNum_list[-1]
        explore_dict[QK] = [Q_new, Q_old]

    if QK == '10-K':
        K_new = AccNum_list[0]
        K_old = AccNum_list[-1]
        explore_dict[QK] = [K_new, K_old]

In [ ]:
QorK ={'10-Q': ['0001564590-20-019706',
  '0001564590-20-002450',
  '0001564590-19-037549',
  '0001564590-19-012709',
  '0001564590-19-001392',
  '0001564590-18-024893',
  '0001564590-18-009307',
  '0001564590-18-001129',
  '0001564590-17-020171',
  '0001564590-17-007547',
  '0001564590-17-000654'],
 '10-K': ['0001564590-19-027952',
  '0001564590-18-019062',
  '0001564590-17-014900']}

In [ ]:
explore_dict

In [ ]:
for QK, N_O in explore_dict.items():
    
    for an_postition, acc_num in enumerate(N_O):
        
        pages = master_filings_dict[acc_num]['filing_documents'][QK]['pages_code']
        print('\n', 'This is {} a {} document.'.format(acc_num, QK))
        test_df_list = table(pages, QK)
        test_df = test_df_list[0]
        
        table_df = test_df.drop(test_df.index[1:]).reset_index(drop=True)
        print('Shape - ', table_df.shape)
        ICD.display(table_df)

In [ ]:
Quarter(['\n\xa0', '\n\xa0', '\nMarch 31,2020', '\n\xa0', '\n\xa0', '\nJune\xa030,2019', '\n\xa0'])

# Save Files Locally.

In [ ]:
Checklist = {}

for k, v in QorK.items():
    value_list = []
    for i, vv in enumerate(v):

        # first grab 10-Q documents only
        pages = master_filings_dict[v[i]]['filing_documents'][k]['pages_code']

        try:
            # Extract Table from html code and wrap it as a list of df.
            test_df_list = table(pages, k)
            test_df = test_df_list[0]
            table_df = test_df.drop(test_df.index[1:]).reset_index(drop=True)
            #ICD.display(table_df[0])

            with open('{}-{}.csv'.format(v[i], k), "wb") as fp:   # Pickling
                pickle.dump(table_df, fp)

            # display a status to the user.
            print('All the pages from {} document {} have been tableized and saved.'.format(k, v[i]))
        
        except: 
            value_list.append(vv)
            print('Something went wrong in file {}, file type = {}'.format(v[i], k))
        
        print('-'*80) 
    Checklist['{}'.format(k)] = value_list
    del value_list

In [ ]:
# Checklist of erroneous filings.  
for a, b in Checklist.items():
    if b != []:
        print('These have a problem.', '\n', a, b)

    else: 
        print(a, 'has no problem!! :) ' , '\n')
    
print(Checklist)

In [ ]:
# Bring QorK over to Part 2. 
QorK